-- Fase D (proyectos): a qué proyecto se imputan las horas de cada día.
--
-- Va numerada V10 y entra DESPUÉS de V8 (adjuntos, fase B2) y V9
-- (calendario, fase C), que están en sus propias ramas. Flyway acepta
-- huecos pero no acepta que aparezca un número menor después de haber
-- aplicado uno mayor, así que el orden de merge es B2 -> C -> D.

-- ---------------------------------------------------------------------
-- btree_gist
-- ---------------------------------------------------------------------
-- Hace falta para el EXCLUDE de más abajo: PostgreSQL sabe indexar
-- rangos en GiST y enteros en B-tree, pero para meter LOS DOS en la
-- misma restricción necesita los operadores B-tree dentro de GiST, y eso
-- es justo lo que añade esta extensión.
--
-- Comprobado antes de escribir esta migración -- que era la condición
-- que dejó anotada el plan -- en los tres sitios donde tiene que
-- funcionar: Neon (btree_gist 1.8 disponible), el Postgres de
-- docker-compose, y la imagen `postgres:18-alpine` que levanta el CI.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------
-- Proyectos
-- ---------------------------------------------------------------------
-- Por empresa, como los departamentos (V7) y los festivos de convenio
-- (V4): dos empresas pueden tener ambas un proyecto "MIGRACION" sin que
-- sea el mismo.
--
-- "codigo" aparte de "nombre" porque es lo que se teclea y lo que se
-- reconoce en un informe ("NX-2026-04"), mientras que el nombre puede
-- ser largo y cambiar sin que cambie el proyecto.
CREATE TABLE proyectos (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id   BIGINT       NOT NULL,
    codigo       VARCHAR(30)  NOT NULL,
    nombre       VARCHAR(150) NOT NULL,
    descripcion  VARCHAR(500),
    fecha_inicio DATE         NOT NULL,
    fecha_fin    DATE,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    version      BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_proyectos_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT uq_proyectos_empresa_codigo UNIQUE (empresa_id, codigo),
    CONSTRAINT ck_proyectos_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE INDEX idx_proyectos_empresa ON proyectos (empresa_id);

-- "activo" y "fecha_fin" NO son lo mismo, y por eso están los dos: un
-- proyecto puede terminar en su fecha prevista (fecha_fin) o cancelarse
-- antes de tiempo (activo = false). Colapsarlos obligaría a inventarse
-- una fecha de fin para algo que se paró sin fecha.

-- ---------------------------------------------------------------------
-- Asignaciones, con vigencia
-- ---------------------------------------------------------------------
-- La decisión que hay detrás: las horas de un día van al proyecto que
-- esa persona tenía asignado ESE día, no al que tiene hoy. Por eso la
-- asignación lleva fechas y no es un simple campo "proyecto_id" en
-- usuarios: con un campo, cambiar a alguien de proyecto en abril
-- recolocaría todas sus horas de enero y reescribiría informes ya
-- cerrados.
--
-- fecha_fin NULL = sigue asignado, sin fecha de salida prevista.
CREATE TABLE asignaciones_proyecto (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id   BIGINT NOT NULL,
    usuario_id   BIGINT NOT NULL,
    proyecto_id  BIGINT NOT NULL,
    fecha_inicio DATE   NOT NULL,
    fecha_fin    DATE,
    version      BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_asignaciones_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asignaciones_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asignaciones_proyecto
        FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE RESTRICT,
    CONSTRAINT ck_asignaciones_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),

    -- Una persona no puede estar en dos proyectos el mismo día.
    --
    -- Va en la BASE y no en el servicio a propósito: comprobarlo en Java
    -- es "leer y luego escribir", es decir, una condición de carrera --
    -- dos asignaciones que llegan a la vez pasan las dos la lectura. Es
    -- exactamente el defecto que la Fase 3 arregló en el resto del
    -- esquema (todo vivía como comprobaciones en código).
    --
    -- COALESCE(fecha_fin, 'infinity') convierte "sigue asignado" en un
    -- rango abierto por la derecha, que es lo que hace que una
    -- asignación sin fin bloquee cualquier otra posterior.
    --
    -- El '[]' incluye los dos extremos, y conviene saber cómo lo
    -- normaliza PostgreSQL: un rango [1/1, 30/6] se guarda como
    -- [1/1, 1/7), así que una asignación que termina el 30/6 y otra que
    -- empieza el 1/7 NO se solapan. Es el comportamiento que se quiere
    -- (el relevo es al día siguiente), y está comprobado con un INSERT
    -- real, no supuesto.
    CONSTRAINT ex_asignaciones_sin_solape EXCLUDE USING gist (
        usuario_id WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'), '[]') WITH &&
    )
);

-- El índice del EXCLUDE ya cubre las consultas por usuario. Estos dos
-- son para las otras dos direcciones: "quién está en este proyecto" y
-- el filtro de tenant.
CREATE INDEX idx_asignaciones_proyecto ON asignaciones_proyecto (proyecto_id);
CREATE INDEX idx_asignaciones_empresa ON asignaciones_proyecto (empresa_id);

-- empresa_id denormalizado en asignaciones (se podría alcanzar por
-- usuario o por proyecto) por el mismo motivo que en "registros" y
-- "peticiones_ausencia" desde la Fase 3: el filtro multi-tenant es lo
-- que va en TODAS las consultas, y alcanzarlo con un JOIN lo convierte
-- en lo más caro de la más barata. Ver ADR 006.

GRANT SELECT, INSERT, UPDATE, DELETE ON proyectos, asignaciones_proyecto TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
