-- Fase E (correcciones con aprobación): ninguna corrección se aplica sola.
--
-- Hasta ahora PATCH /api/v1/fichaje/{id} corregía EN EL ACTO: anulaba el
-- registro original y creaba uno nuevo con las horas que dijera RRHH. El
-- dueño del fichaje se enteraba, como mucho, mirando la auditoría.
--
-- Eso choca con lo que la auditoría inmutable (V5) pretende garantizar:
-- de poco sirve que la traza no se pueda alterar si el dato que traza se
-- puede cambiar sin que el interesado lo sepa ni pueda oponerse. A
-- partir de aquí, una corrección es una SOLICITUD que alguien aprueba, y
-- el registro no se toca mientras está pendiente. Ver ADR 010.

-- ---------------------------------------------------------------------
-- Solicitudes de corrección
-- ---------------------------------------------------------------------
CREATE TABLE solicitudes_correccion (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id             BIGINT      NOT NULL,
    registro_id            BIGINT      NOT NULL,
    solicitante_id         BIGINT      NOT NULL,

    hora_entrada_propuesta TIMESTAMPTZ NOT NULL,
    hora_salida_propuesta  TIMESTAMPTZ NOT NULL,
    motivo                 TEXT        NOT NULL,

    estado                 VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',

    -- Los tres de la resolución van juntos: o los tres con valor, o los
    -- tres vacíos. Es la misma regla que ck_peticiones_resolucion_coherente
    -- en las ausencias (V4), y por el mismo motivo: una petición resuelta
    -- SIEMPRE tiene quién y cuándo.
    aprobador_id           BIGINT,
    fecha_resolucion       TIMESTAMPTZ,
    comentario_resolucion  TEXT,

    -- Solo cuando el dueño del fichaje no acepta la corrección que le han
    -- propuesto. Es lo que lleva la solicitud a EN_DISPUTA.
    motivo_disputa         TEXT,

    creado_en              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_correcciones_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_correcciones_registro
        FOREIGN KEY (registro_id) REFERENCES registros(id) ON DELETE RESTRICT,
    CONSTRAINT fk_correcciones_solicitante
        FOREIGN KEY (solicitante_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_correcciones_aprobador
        FOREIGN KEY (aprobador_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_correcciones_estado
        CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'EN_DISPUTA')),

    CONSTRAINT ck_correcciones_horas
        CHECK (hora_salida_propuesta > hora_entrada_propuesta),

    -- Igual que en las ausencias: resuelta = con resolutor y fecha.
    -- EN_DISPUTA cuenta como NO resuelta -- sigue esperando a alguien.
    CONSTRAINT ck_correcciones_resolucion_coherente CHECK (
        (estado IN ('PENDIENTE', 'EN_DISPUTA')
             AND aprobador_id IS NULL AND fecha_resolucion IS NULL)
        OR
        (estado IN ('APROBADA', 'RECHAZADA')
             AND aprobador_id IS NOT NULL AND fecha_resolucion IS NOT NULL)
    ),

    -- Una disputa sin motivo no es una disputa: el motivo es lo que RRHH
    -- lee para resolver en firme.
    CONSTRAINT ck_correcciones_disputa_con_motivo
        CHECK (estado <> 'EN_DISPUTA' OR motivo_disputa IS NOT NULL)
);

-- Un fichaje no puede tener DOS solicitudes vivas a la vez.
--
-- Índice único PARCIAL y no UNIQUE(registro_id) a secas: un mismo
-- fichaje puede acumular varias solicitudes a lo largo del tiempo (una
-- rechazada, otra nueva), pero solo una esperando resolución. Con un
-- UNIQUE normal, el segundo intento fallaría para siempre.
--
-- EN_DISPUTA también ocupa: la solicitud sigue viva, esperando a RRHH.
CREATE UNIQUE INDEX uq_correcciones_una_viva_por_registro
    ON solicitudes_correccion (registro_id)
    WHERE estado IN ('PENDIENTE', 'EN_DISPUTA');

CREATE INDEX idx_correcciones_empresa_estado ON solicitudes_correccion (empresa_id, estado);
CREATE INDEX idx_correcciones_solicitante ON solicitudes_correccion (solicitante_id);

-- ---------------------------------------------------------------------
-- La auditoría gana tres acciones
-- ---------------------------------------------------------------------
-- V3 creó la columna con CHECK (accion IN (...)) sobre cuatro valores y
-- VARCHAR(20). Las dos cosas se quedan cortas:
--
--  - Sin ampliar el CHECK, el primer INSERT con un valor nuevo revienta
--    con una violación de restricción, y encima dentro del listener de
--    auditoría.
--  - 'SOLICITUD_CORRECCION' mide EXACTAMENTE 20 caracteres. Cabría por
--    los pelos, y cualquier acción futura un poco más larga no. Se sube
--    a 30 para no volver a tocarlo.
ALTER TABLE auditoria_fichaje ALTER COLUMN accion TYPE VARCHAR(30);

ALTER TABLE auditoria_fichaje DROP CONSTRAINT auditoria_fichaje_accion_check;
ALTER TABLE auditoria_fichaje ADD CONSTRAINT auditoria_fichaje_accion_check
    CHECK (accion IN (
        'CREACION',
        'MODIFICACION',
        'CORRECCION',
        'ANULACION',
        'SOLICITUD_CORRECCION',
        'RECHAZO_CORRECCION',
        'DISPUTA'
    ));

-- ---------------------------------------------------------------------
-- Avisos nuevos
-- ---------------------------------------------------------------------
-- Cada fase que añade un tipo de aviso tiene que ampliar este CHECK, o
-- el INSERT del listener falla en silencio dentro de su @Async.
--
-- La ruta de destino es LÓGICA, no una ruta de Compose: Android la
-- traduce en DestinoDeAviso.kt (ver fase A).
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA'
));

GRANT SELECT, INSERT, UPDATE, DELETE ON solicitudes_correccion TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
