-- Fase F (horas extra): detectar los excesos de jornada y llevar la
-- cuenta anual del art. 35.2 ET.
--
-- Va numerada V12 y entra DESPUÉS de la V11 (correcciones con
-- aprobación, fase E), que está en su propia rama. Flyway no acepta que
-- aparezca un número menor después de haber aplicado uno mayor.

-- ---------------------------------------------------------------------
-- Avisos de horas extra
-- ---------------------------------------------------------------------
-- Es un AVISO, no una imputación: el proceso nocturno detecta que una
-- jornada (o una semana) se pasó del umbral y lo deja anotado para que
-- alguien lo mire. Lo que decide si esas horas son extra de verdad es la
-- revisión humana, no el reloj: un exceso puede ser una jornada
-- intensiva pactada, un turno partido mal fichado o una corrección
-- pendiente.
CREATE TABLE avisos_horas_extra (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id    BIGINT      NOT NULL,
    usuario_id    BIGINT      NOT NULL,

    -- El fichaje que disparó el aviso. NULL en los semanales: ahí el
    -- exceso no es de una jornada concreta sino de la suma de varias,
    -- y señalar a una cualquiera sería arbitrario.
    registro_id   BIGINT,

    -- Para un aviso DIARIA, el día. Para uno SEMANAL, el LUNES de esa
    -- semana: así la fecha identifica el periodo sin necesidad de dos
    -- columnas más.
    fecha         DATE        NOT NULL,
    minutos_extra INTEGER     NOT NULL CHECK (minutos_extra > 0),

    -- Contra qué listón se comparó. Se GUARDA en vez de recalcularse al
    -- leer, y no es redundancia: en un aviso semanal esta cifra es la
    -- mitad de la explicación ("esa semana tenía 4 días hábiles, se
    -- esperaban 30 h"). Recalcularla después daría otro número en cuanto
    -- alguien añada un festivo de convenio o apruebe una ausencia con
    -- efecto retroactivo, y el aviso dejaría de cuadrar con la razón por
    -- la que se creó.
    minutos_esperados INTEGER NOT NULL CHECK (minutos_esperados >= 0),

    tipo          VARCHAR(10) NOT NULL,
    estado        VARCHAR(15) NOT NULL DEFAULT 'ABIERTO',

    justificacion TEXT,
    revisado_por  BIGINT,
    fecha_revision TIMESTAMPTZ,

    creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version       BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_horas_extra_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_horas_extra_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_horas_extra_registro
        FOREIGN KEY (registro_id) REFERENCES registros(id) ON DELETE RESTRICT,
    CONSTRAINT fk_horas_extra_revisor
        FOREIGN KEY (revisado_por) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_horas_extra_tipo CHECK (tipo IN ('DIARIA', 'SEMANAL')),
    CONSTRAINT ck_horas_extra_estado CHECK (estado IN ('ABIERTO', 'JUSTIFICADO', 'ACEPTADO')),

    -- Revisado = con revisor y fecha, igual que las ausencias (V4) y las
    -- correcciones (V11).
    CONSTRAINT ck_horas_extra_revision_coherente CHECK (
        (estado = 'ABIERTO' AND revisado_por IS NULL AND fecha_revision IS NULL)
        OR
        (estado <> 'ABIERTO' AND revisado_por IS NOT NULL AND fecha_revision IS NOT NULL)
    ),

    -- Un aviso DIARIA nace de una jornada concreta; uno SEMANAL, no.
    CONSTRAINT ck_horas_extra_registro_segun_tipo
        CHECK ((tipo = 'DIARIA') = (registro_id IS NOT NULL))
);

-- El proceso nocturno corre todos los días y vuelve a mirar los mismos
-- días si algo cambió (una corrección de la fase E puede alterar una
-- jornada del mes pasado). Sin esto crearía un aviso duplicado en cada
-- pasada.
--
-- La clave es (usuario, fecha, tipo) y no incluye el estado: si alguien
-- ya justificó el exceso del martes, la siguiente pasada no debe volver
-- a abrirlo.
CREATE UNIQUE INDEX uq_horas_extra_usuario_fecha_tipo
    ON avisos_horas_extra (usuario_id, fecha, tipo);

CREATE INDEX idx_horas_extra_empresa_estado ON avisos_horas_extra (empresa_id, estado);
CREATE INDEX idx_horas_extra_usuario_fecha ON avisos_horas_extra (usuario_id, fecha);

-- ---------------------------------------------------------------------
-- Por qué NO hay una tabla de "bolsa anual"
-- ---------------------------------------------------------------------
-- El art. 35.2 ET limita las horas extra a 80 al año. Lo natural sería
-- un contador por usuario y año, y sería un error: se desincroniza en
-- cuanto una corrección cambia una jornada del mes pasado -- y desde la
-- fase E las correcciones son rutina, no una excepción.
--
-- La bolsa se DERIVA de los avisos aceptados al leerla, igual que el
-- saldo de vacaciones deriva de las ausencias aprobadas (ver V4 y
-- VacationBalanceService). Una sola fuente de verdad.

-- ---------------------------------------------------------------------
-- Avisos nuevos
-- ---------------------------------------------------------------------
-- 🚨 Este CHECK se REEMPLAZA entero, así que hay que volver a listar
-- TODOS los tipos, no solo los que añade esta fase.
--
-- Es una trampa que no se ve en el diff: la fase E (V11) añade los tres
-- de correcciones, y si aquí se listaran solo los de las fases A y F,
-- aplicar V11 y luego V12 dejaría el CHECK sin ellos. Los avisos de
-- correcciones empezarían a fallar dentro del listener @Async, en
-- silencio, y el síntoma aparecería lejos de la causa.
--
-- Se listan los ocho. Si esta migración se aplicara sin la V11, los tres
-- de correcciones sobrarían en el CHECK y no pasaría nada: un valor
-- permitido que nadie usa es inofensivo.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE'
));

GRANT SELECT, INSERT, UPDATE, DELETE ON avisos_horas_extra TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
