-- Fase G (canal de denuncias): el canal interno de información que la
-- Ley 2/2023 obliga a tener.
--
-- No es un buzón de sugerencias. La ley fija tres cosas que el esquema
-- tiene que sostener, y ninguna es opcional:
--
--   1. Anonimato OPCIONAL y de verdad (art. 7.3). Si el denunciante
--      elige no identificarse, el sistema no puede saber quién es --
--      tampoco a posteriori, tampoco mirando la base de datos.
--   2. Acuse de recibo en 7 días naturales y respuesta en 3 meses
--      (art. 9.2). Los plazos se CALCULAN al leer; aquí solo se guardan
--      las fechas de los hechos.
--   3. Un Responsable del Sistema Interno de Información (art. 8) que
--      es el único que las lee. En este proyecto, ADMIN.
--
-- Va numerada V13 y no V12 como decía el plan: la fase F ya se llevó el
-- V12. Ver ADR 012.

-- ---------------------------------------------------------------------
-- Denuncias
-- ---------------------------------------------------------------------
CREATE TABLE denuncias (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id        BIGINT      NOT NULL,

    -- El HASH del código de seguimiento, no el código.
    --
    -- El código es la credencial con la que un denunciante anónimo
    -- vuelve a entrar en su expediente: quien lo tiene, lee la denuncia
    -- y escribe en ella. Eso lo pone en la misma categoría que una
    -- contraseña, y guardarlo en claro significaría que cualquiera con
    -- acceso de lectura a la base -- una copia de seguridad, un volcado
    -- de soporte -- puede suplantar al denunciante en cualquier
    -- expediente abierto.
    --
    -- SHA-256 SIN SAL, y la ausencia de sal es deliberada: la búsqueda
    -- tiene que ser por igualdad sobre un índice (llega el código y hay
    -- que encontrar SU fila), y una sal por fila obligaría a recorrer la
    -- tabla entera probando. Lo que hace aceptable prescindir de ella es
    -- que esto no es una contraseña elegida por una persona sino un
    -- UUIDv4 de 122 bits de entropía: no hay diccionario que atacar ni
    -- tabla arcoíris que precomputar. El razonamiento no vale para
    -- 'usuarios.password', que sigue con BCrypt donde le corresponde.
    --
    -- VARCHAR(64) y no CHAR(64), aunque el hash mida siempre 64: la
    -- validación de esquema de Hibernate compara el TIPO, y un CHAR
    -- llega como `bpchar` mientras que un String de JPA espera
    -- `varchar`. Con CHAR la aplicación no arranca -- falla al construir
    -- el SessionFactory, antes de servir una sola petición.
    codigo_hash       VARCHAR(64) NOT NULL,

    -- NULL = anónima. Y NULL de verdad: no hay columna "oculto" con el
    -- id al lado, porque un dato que existe acaba consultándose.
    denunciante_id    BIGINT,

    categoria         VARCHAR(20) NOT NULL,
    descripcion       TEXT        NOT NULL,
    estado            VARCHAR(20) NOT NULL DEFAULT 'RECIBIDA',

    creado_en         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Cuándo el instructor tocó el expediente por primera vez (un
    -- mensaje o un cambio de estado, lo que ocurra antes). Es el hecho
    -- que la ley llama acuse de recibo. Se guarda la FECHA del hecho; el
    -- "te quedan 3 días" se calcula al leer, porque un plazo guardado
    -- envejece mal.
    acuse_recibo_en   TIMESTAMPTZ,

    -- Cuándo se cerró, sea resuelta o archivada.
    resuelta_en       TIMESTAMPTZ,

    -- Qué se concluyó. Obligatoria al cerrar: cerrar una denuncia sin
    -- decir en qué quedó deja al denunciante sin nada, y es justo lo que
    -- la ley pretende evitar al exigir una respuesta.
    conclusion        TEXT,

    version           BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_denuncias_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,

    -- RESTRICT y no SET NULL: convertir una denuncia identificada en
    -- anónima al dar de baja al denunciante parece elegante y es un
    -- borrado de prueba. Las bajas en este proyecto son lógicas
    -- (usuarios.activo), así que la fila nunca desaparece.
    CONSTRAINT fk_denuncias_denunciante
        FOREIGN KEY (denunciante_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT uq_denuncias_codigo UNIQUE (codigo_hash),

    CONSTRAINT ck_denuncias_categoria CHECK (categoria IN (
        'ACOSO', 'DISCRIMINACION', 'FRAUDE', 'SEGURIDAD', 'CORRUPCION',
        'PROTECCION_DATOS', 'OTRA'
    )),

    CONSTRAINT ck_denuncias_estado CHECK (estado IN (
        'RECIBIDA', 'EN_INVESTIGACION', 'RESUELTA', 'ARCHIVADA'
    )),

    -- Cerrada = con fecha de cierre y con conclusión. Las dos, o
    -- ninguna: una denuncia "resuelta" sin conclusión no responde nada.
    CONSTRAINT ck_denuncias_cierre_coherente CHECK (
        (estado IN ('RECIBIDA', 'EN_INVESTIGACION')
             AND resuelta_en IS NULL AND conclusion IS NULL)
        OR
        (estado IN ('RESUELTA', 'ARCHIVADA')
             AND resuelta_en IS NOT NULL AND conclusion IS NOT NULL)
    ),

    -- No se puede cerrar lo que no se ha acusado: si hay cierre, hubo
    -- acuse antes. Evita que un PATCH que salte de RECIBIDA a RESUELTA
    -- deje el expediente sin la fecha que la ley exige registrar.
    CONSTRAINT ck_denuncias_acuse_antes_del_cierre CHECK (
        resuelta_en IS NULL OR acuse_recibo_en IS NOT NULL
    )
);

-- La bandeja del instructor: las de su empresa, por estado.
CREATE INDEX idx_denuncias_empresa_estado ON denuncias (empresa_id, estado);

-- "Mis denuncias" de quien SÍ se identificó. Parcial porque la mayoría
-- de las filas puede tener denunciante_id NULL y esas no se buscan nunca
-- por aquí -- a una anónima solo se llega por el código.
CREATE INDEX idx_denuncias_denunciante ON denuncias (denunciante_id)
    WHERE denunciante_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- Mensajes del expediente
-- ---------------------------------------------------------------------
-- La conversación entre el denunciante y quien instruye. Es lo que
-- permite pedir una aclaración sin saber a quién se le está pidiendo.
CREATE TABLE denuncia_mensajes (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denuncia_id  BIGINT      NOT NULL,

    -- Quién habla: el denunciante o el instructor.
    --
    -- Hace falta una columna porque autor_id NO sirve para distinguirlo.
    -- En una denuncia anónima el mensaje del denunciante va con autor_id
    -- NULL, y sin este campo un NULL sería indistinguible de un dato que
    -- falta. Además es lo que se pinta en la pantalla, y pintarlo a
    -- partir de "¿tiene autor?" ataría la presentación al anonimato.
    autor_rol    VARCHAR(15) NOT NULL,

    -- NULL siempre que el mensaje venga del denunciante de una denuncia
    -- anónima, AUNQUE estuviera autenticado al escribirlo -- que lo
    -- está, porque el canal vive dentro de la aplicación. Guardar aquí
    -- su id "por trazabilidad" desharía el anonimato de la denuncia
    -- entera en el primer mensaje de seguimiento.
    autor_id     BIGINT,

    texto        TEXT        NOT NULL,
    creado_en    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_denuncia_mensajes_denuncia
        FOREIGN KEY (denuncia_id) REFERENCES denuncias(id) ON DELETE CASCADE,
    CONSTRAINT fk_denuncia_mensajes_autor
        FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_denuncia_mensajes_autor_rol
        CHECK (autor_rol IN ('DENUNCIANTE', 'INSTRUCTOR')),

    -- El instructor NUNCA es anónimo: quien instruye responde de lo que
    -- escribe. El denunciante puede serlo o no, así que ahí no se exige
    -- nada.
    CONSTRAINT ck_denuncia_mensajes_instructor_identificado
        CHECK (autor_rol <> 'INSTRUCTOR' OR autor_id IS NOT NULL)
);

CREATE INDEX idx_denuncia_mensajes_denuncia ON denuncia_mensajes (denuncia_id, creado_en);

-- ---------------------------------------------------------------------
-- Avisos nuevos
-- ---------------------------------------------------------------------
-- 🚨 Este CHECK se REEMPLAZA entero: hay que volver a listar TODOS los
-- tipos, no solo los dos que añade esta fase. Listar de menos no falla
-- al migrar -- falla después, dentro del listener @Async, en silencio.
--
-- Van diez: 3 de la A, 3 de la E, 2 de la F y 2 de aquí.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA'
));

GRANT SELECT, INSERT, UPDATE, DELETE ON denuncias TO nxtime_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON denuncia_mensajes TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
