-- Fase H (ofertas internas y candidaturas): la promoción interna, y el
-- CV que se congela con ella.
--
-- Va numerada V14 y no V13 como decía el plan: la fase G ya se llevó el
-- V13. Ver ADR 013.

-- ---------------------------------------------------------------------
-- Primero, la deuda que la fase B2 dejó anotada
-- ---------------------------------------------------------------------
-- V8 dice, literalmente: "OJO para la fase H: una candidatura congela el
-- adjunto_id del CV de ese momento, así que el reemplazo tendrá que
-- dejar de borrar la fila vieja cuando alguien la referencie". Es esto.
--
-- Hasta ahora subir un CV nuevo BORRABA el anterior, y el UNIQUE
-- (usuario_id, tipo) era lo que garantizaba "uno vigente por persona".
-- Con candidaturas de por medio ese borrado destruiría lo que un gestor
-- leyó en enero: en marzo el candidato sube otra versión y el
-- expediente de su candidatura cambia solo, o se queda sin CV.
--
-- La salida no es dejar de reemplazar sino separar las dos ideas que el
-- UNIQUE mezclaba: "existe" y "es el vigente". El CV viejo referenciado
-- por una candidatura SIGUE EXISTIENDO, deja de estar vigente, y el
-- índice único pasa a ser PARCIAL.
ALTER TABLE adjuntos ADD COLUMN vigente BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE adjuntos DROP CONSTRAINT uq_adjuntos_usuario_tipo;

-- Uno vigente por persona y tipo; los anteriores, los que hagan falta.
-- Un adjunto NO vigente no se lista en el perfil ni se puede volver a
-- elegir: solo se llega a él desde la candidatura que lo congeló.
CREATE UNIQUE INDEX uq_adjuntos_usuario_tipo_vigente
    ON adjuntos (usuario_id, tipo)
    WHERE vigente;

-- ---------------------------------------------------------------------
-- Ofertas internas
-- ---------------------------------------------------------------------
CREATE TABLE ofertas_internas (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,

    titulo          VARCHAR(150) NOT NULL,
    descripcion     TEXT         NOT NULL,
    puesto          VARCHAR(100),

    -- A qué departamento pertenece la vacante. Opcional: una empresa
    -- pequeña puede no tener departamentos dados de alta, y obligar a
    -- crear uno para publicar una oferta sería inventarse organigrama.
    departamento_id BIGINT,

    publicada_por   BIGINT       NOT NULL,

    -- Cuándo se publicó. NULL mientras está en BORRADOR: una oferta que
    -- nadie ha visto todavía no tiene fecha de publicación, y ponerle la
    -- de creación haría que la lista mintiera sobre su antigüedad.
    fecha_publicacion TIMESTAMPTZ,

    -- Hasta cuándo se admiten candidaturas. Opcional: hay vacantes que
    -- se cierran cuando aparece la persona, no en una fecha.
    fecha_cierre    DATE,

    estado          VARCHAR(10)  NOT NULL DEFAULT 'BORRADOR',

    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version         BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_ofertas_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ofertas_departamento
        FOREIGN KEY (departamento_id) REFERENCES departamentos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ofertas_publicada_por
        FOREIGN KEY (publicada_por) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_ofertas_estado
        CHECK (estado IN ('BORRADOR', 'ABIERTA', 'CERRADA')),

    -- Publicada = con fecha de publicación. Una oferta que salió del
    -- borrador y no la tiene no se puede ordenar ni fechar, y volver a
    -- BORRADOR no la borra: la fecha se queda como constancia de que
    -- estuvo publicada.
    CONSTRAINT ck_ofertas_publicacion_coherente
        CHECK (estado = 'BORRADOR' OR fecha_publicacion IS NOT NULL)
);

CREATE INDEX idx_ofertas_empresa_estado ON ofertas_internas (empresa_id, estado);

-- ---------------------------------------------------------------------
-- Candidaturas
-- ---------------------------------------------------------------------
CREATE TABLE candidaturas (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oferta_id     BIGINT      NOT NULL,
    usuario_id    BIGINT      NOT NULL,

    -- El CV TAL COMO ESTABA al presentarse, no "el CV de esta persona".
    --
    -- Es la decisión de la fase. Si esto apuntara al usuario, subir una
    -- versión nueva en marzo cambiaría lo que el gestor leyó en enero:
    -- el expediente de una candidatura dejaría de ser un expediente. Por
    -- eso apunta al adjunto concreto, y por eso el RESTRICT: ese CV ya no
    -- se puede destruir mientras la candidatura exista.
    --
    -- NOT NULL: no se puede optar a una vacante interna sin CV. La app
    -- lo dice antes de dejar pulsar el botón, en vez de aceptarla y
    -- dejar al gestor con una candidatura vacía.
    adjunto_cv_id BIGINT      NOT NULL,

    carta         TEXT,
    estado        VARCHAR(15) NOT NULL DEFAULT 'RECIBIDA',

    -- Quién y cuándo movió la candidatura por última vez. Mismo criterio
    -- que en ausencias (V4), correcciones (V11) y denuncias (V13):
    -- resuelta = con responsable y fecha.
    resuelta_por  BIGINT,
    fecha_resolucion TIMESTAMPTZ,
    comentario    TEXT,

    creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version       BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_candidaturas_oferta
        FOREIGN KEY (oferta_id) REFERENCES ofertas_internas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_candidaturas_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    -- 🚨 El RESTRICT que hace cumplir lo de arriba, y el motivo por el
    -- que existe la columna `adjuntos.vigente`: a partir de aquí, la
    -- base IMPIDE borrar un CV que una candidatura haya congelado. El
    -- servicio lo comprueba antes para dar un mensaje que se entienda,
    -- pero quien lo garantiza es esta línea.
    CONSTRAINT fk_candidaturas_cv
        FOREIGN KEY (adjunto_cv_id) REFERENCES adjuntos(id) ON DELETE RESTRICT,

    CONSTRAINT fk_candidaturas_resolutor
        FOREIGN KEY (resuelta_por) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_candidaturas_estado
        CHECK (estado IN ('RECIBIDA', 'EN_PROCESO', 'DESCARTADA', 'SELECCIONADA')),

    -- Movida de RECIBIDA = con quién y cuándo.
    CONSTRAINT ck_candidaturas_resolucion_coherente CHECK (
        (estado = 'RECIBIDA' AND resuelta_por IS NULL AND fecha_resolucion IS NULL)
        OR
        (estado <> 'RECIBIDA' AND resuelta_por IS NOT NULL AND fecha_resolucion IS NOT NULL)
    ),

    -- Una candidatura por persona y oferta. No es una restricción
    -- burocrática: sin ella, pulsar dos veces el botón deja al gestor
    -- dos expedientes de la misma persona con dos CV distintos.
    CONSTRAINT uq_candidaturas_oferta_usuario UNIQUE (oferta_id, usuario_id)
);

CREATE INDEX idx_candidaturas_usuario ON candidaturas (usuario_id);
CREATE INDEX idx_candidaturas_oferta_estado ON candidaturas (oferta_id, estado);

-- ---------------------------------------------------------------------
-- Avisos nuevos
-- ---------------------------------------------------------------------
-- 🚨 Este CHECK se REEMPLAZA entero: hay que volver a listar TODOS los
-- tipos, no solo los tres que añade esta fase. Listar de menos no falla
-- al migrar -- falla después, dentro del listener @Async, en silencio.
--
-- Van trece: 3 de la A, 3 de la E, 2 de la F, 2 de la G y 3 de aquí.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA',
    -- Fase H
    'OFERTA_PUBLICADA',
    'CANDIDATURA_RECIBIDA',
    'CANDIDATURA_ACTUALIZADA'
));

GRANT SELECT, INSERT, UPDATE, DELETE ON ofertas_internas TO nxtime_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON candidaturas TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
