-- Paso 5 del piloto (monitorización): constancia de que las tareas
-- nocturnas han corrido.
--
-- Las dos tareas programadas (el cierre de jornadas olvidadas a las 3:00 y
-- el barrido de horas extra a las 3:30) corren DENTRO del proceso, con el
-- programador de Spring. Si a esa hora el proceso no está vivo, no corren,
-- y nada lo dice: en Render gratuito el servicio se duerme a los 15 minutos
-- sin tráfico, así que hasta que existió el keep-alive (09/2026) lo más
-- probable es que no hubieran corrido casi nunca. Un reinicio o un
-- despliegue a las 3:00 tiene el mismo efecto.
--
-- Esta tabla es el registro que lo hace visible: cada ejecución deja una
-- fila al empezar (EN_CURSO) y la cierra al terminar (OK o ERROR). Una fila
-- que se queda EN_CURSO es un proceso que murió a mitad.

CREATE TABLE ejecuciones_tarea (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarea      VARCHAR(30)   NOT NULL,
    inicio     TIMESTAMPTZ   NOT NULL,
    fin        TIMESTAMPTZ,
    resultado  VARCHAR(10)   NOT NULL,
    -- Resumen legible ("Cerradas 3 jornadas...") o el motivo del fallo.
    -- No sale nunca por /estado/tareas, que es público.
    detalle    VARCHAR(2000),

    -- Añadir una tarea exige ampliar esta lista (ver ScheduledTask).
    CONSTRAINT ck_ejecuciones_tarea_tarea
        CHECK (tarea IN ('CIERRE_JORNADAS', 'HORAS_EXTRA')),
    CONSTRAINT ck_ejecuciones_tarea_resultado
        CHECK (resultado IN ('EN_CURSO', 'OK', 'ERROR')),
    -- Terminada si y solo si tiene hora de fin: una fila OK sin fin, o
    -- EN_CURSO con fin, sería un registro que miente.
    CONSTRAINT ck_ejecuciones_tarea_fin
        CHECK ((resultado = 'EN_CURSO') = (fin IS NULL) AND (fin IS NULL OR fin >= inicio))
);

-- La consulta de /estado/tareas: la última de cada tarea, y si hay alguna
-- correcta desde una hora dada.
CREATE INDEX ix_ejecuciones_tarea_tarea_inicio ON ejecuciones_tarea (tarea, inicio DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON ejecuciones_tarea TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
