-- Recuperación de contraseña y primer acceso (fase 1 del plan "de demo a
-- app usable", 09/2026). Ver ADR 014.
--
-- Hasta aquí la contraseña de cada empleado la tecleaba quien le daba de
-- alta, y quien la olvidaba se quedaba fuera para siempre: no había forma
-- de recuperarla sin tocar la base a mano. Las dos cosas se resuelven con
-- lo mismo: un código de un solo uso que llega por correo y con el que la
-- propia persona elige su contraseña.
--
-- Del código solo se guarda el hash, como del código de seguimiento de las
-- denuncias (V13), pero con BCrypt y no con SHA-256: aquel se busca POR el
-- código y necesitaba un hash determinista; este se busca por el usuario, y
-- seis dígitos pasados por SHA-256 se sacarían por fuerza bruta en segundos
-- si la tabla se filtrara.

CREATE TABLE codigos_acceso (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT       NOT NULL,
    tipo               VARCHAR(20)  NOT NULL,
    codigo_hash        VARCHAR(100) NOT NULL,
    creado_en          TIMESTAMPTZ  NOT NULL,
    expira_en          TIMESTAMPTZ  NOT NULL,

    -- Seis dígitos son un millón de combinaciones, y lo que las protege no
    -- es el tamaño sino que no se pueden probar: cada código admite pocos
    -- intentos (ver AccessCode.MAXIMO_INTENTOS).
    intentos_fallidos  INT          NOT NULL DEFAULT 0,

    usado_en           TIMESTAMPTZ,

    -- Se anula al emitir otro para la misma persona (solo vale el último)
    -- o al agotar los intentos. Anular y no borrar: los anulados siguen
    -- contando para el límite de códigos por hora.
    anulado_en         TIMESTAMPTZ,

    CONSTRAINT fk_codigos_acceso_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT ck_codigos_acceso_tipo CHECK (tipo IN ('ALTA', 'RECUPERACION')),
    CONSTRAINT ck_codigos_acceso_intentos CHECK (intentos_fallidos >= 0),
    CONSTRAINT ck_codigos_acceso_caducidad CHECK (expira_en > creado_en)
);

-- El código vigente de una persona, y cuántos se le han emitido en la
-- última hora.
CREATE INDEX ix_codigos_acceso_usuario_creado ON codigos_acceso (usuario_id, creado_en DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON codigos_acceso TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
