-- Añadir una pausa a posteriori (09/2026). Ver ADR 015.
--
-- El caso: "se me olvidó darle a pausar para comer". Hasta aquí una pausa
-- solo existía si se pulsaba el botón en el momento, y lo que se guardaba
-- era un CONTADOR (registros.segundos_pausa_acumulados): ni inicio, ni fin,
-- ni autor.
--
-- ⚠️ Va DETRÁS de V17 y V18, que están en PR sin mergear al escribir esto.
-- Flyway no aplica una migración más antigua que la última aplicada: si
-- esta llegara a producción antes que aquellas, las dos se quedarían sin
-- aplicar y el arranque fallaría la validación.
--
-- El contador NO cambia de significado: sigue siendo el total que leen los
-- agregados nativos, el mapper y la app. Lo que se añade es un LIBRO con
-- las pausas que una persona metió a mano, porque esas SÍ tienen intervalo:
--
--  - Solo sumar al contador dejaría un número que salta de 0 a 3600 sin
--    intervalo y sin autor consultable, que es justo lo que la inspección
--    mira mal. Y sin intervalo no hay forma de detectar un solape.
--  - Una tabla de intervalos para TODAS las pausas obligaría a inventarse
--    los de las pausas históricas, que no están en ninguna parte. En un
--    registro de conservación obligatoria de 4 años (RD-ley 8/2019), eso
--    es falsificar.

CREATE TABLE pausas_anadidas (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,

    -- El fichaje al que pertenece AHORA. Si una corrección lo sustituye por
    -- una versión nueva, la pausa se muda con él (ver CorrectionServiceImpl).
    registro_id     BIGINT       NOT NULL,

    inicio          TIMESTAMPTZ  NOT NULL,
    fin             TIMESTAMPTZ  NOT NULL,
    motivo          TEXT         NOT NULL,

    creada_por_id   BIGINT       NOT NULL,
    creada_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- NULL = se aplicó directamente, sin aprobación. Con valor = entró al
    -- aprobarse esa solicitud de corrección.
    solicitud_id    BIGINT,

    -- Deshacer NO borra: marca. El libro es de solo añadir, como la traza.
    anulada         BOOLEAN      NOT NULL DEFAULT FALSE,
    anulada_por_id  BIGINT,
    anulada_en      TIMESTAMPTZ,

    CONSTRAINT fk_pausas_empresa    FOREIGN KEY (empresa_id)     REFERENCES empresas(id)               ON DELETE RESTRICT,
    CONSTRAINT fk_pausas_registro   FOREIGN KEY (registro_id)    REFERENCES registros(id)              ON DELETE RESTRICT,
    CONSTRAINT fk_pausas_creada_por FOREIGN KEY (creada_por_id)  REFERENCES usuarios(id)               ON DELETE RESTRICT,
    CONSTRAINT fk_pausas_solicitud  FOREIGN KEY (solicitud_id)   REFERENCES solicitudes_correccion(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pausas_anulada_por FOREIGN KEY (anulada_por_id) REFERENCES usuarios(id)              ON DELETE RESTRICT,

    CONSTRAINT ck_pausas_intervalo CHECK (fin > inicio),

    -- Anulada = con quién y cuándo, sin excepción. Misma regla que las
    -- resoluciones de ausencias y correcciones.
    CONSTRAINT ck_pausas_anulacion_coherente CHECK (
        (anulada = FALSE AND anulada_por_id IS NULL AND anulada_en IS NULL)
        OR
        (anulada = TRUE AND anulada_por_id IS NOT NULL AND anulada_en IS NOT NULL)
    )
);

CREATE INDEX idx_pausas_registro_vivas ON pausas_anadidas (registro_id) WHERE anulada = FALSE;

-- ---------------------------------------------------------------------
-- Pedir una pausa sobre un día pasado va por el mecanismo de correcciones
-- ---------------------------------------------------------------------
-- Dos columnas en la tabla que ya existe, y NO una tabla paralela de
-- "solicitudes de pausa": duplicaría aprobar, rechazar, disputar y avisar,
-- y sobre todo dejaría convivir una petición de pausa y una de horas sobre
-- el mismo fichaje, que es justo lo que uq_correcciones_una_viva_por_registro
-- existe para impedir.
ALTER TABLE solicitudes_correccion ADD COLUMN pausa_inicio_propuesta TIMESTAMPTZ;
ALTER TABLE solicitudes_correccion ADD COLUMN pausa_fin_propuesta    TIMESTAMPTZ;

-- Las dos o ninguna, y si van, en orden. Que la pausa quepa dentro de las
-- horas propuestas lo comprueba el servicio: aquí sería un CHECK sobre
-- tres columnas que además tendría que conocer las pausas ya acumuladas.
ALTER TABLE solicitudes_correccion ADD CONSTRAINT ck_correcciones_pausa CHECK (
    (pausa_inicio_propuesta IS NULL AND pausa_fin_propuesta IS NULL)
    OR
    (pausa_inicio_propuesta IS NOT NULL AND pausa_fin_propuesta IS NOT NULL
        AND pausa_fin_propuesta > pausa_inicio_propuesta)
);

-- ---------------------------------------------------------------------
-- La auditoría gana dos acciones
-- ---------------------------------------------------------------------
-- 🚨 El CHECK se reemplaza ENTERO: van las siete de V11 más las dos nuevas.
-- La columna ya es VARCHAR(30) desde V11; las nuevas miden 13.
ALTER TABLE auditoria_fichaje DROP CONSTRAINT auditoria_fichaje_accion_check;
ALTER TABLE auditoria_fichaje ADD CONSTRAINT auditoria_fichaje_accion_check
    CHECK (accion IN (
        'CREACION',
        'MODIFICACION',
        'CORRECCION',
        'ANULACION',
        'SOLICITUD_CORRECCION',
        'RECHAZO_CORRECCION',
        'DISPUTA',
        'PAUSA_ANADIDA',
        'PAUSA_ANULADA'
    ));

-- Sin DELETE: el libro es de solo añadir. Deshacer una pausa es marcarla
-- anulada, y así la aplicación no podría borrar una fila aunque lo intentara.
GRANT SELECT, INSERT, UPDATE ON pausas_anadidas TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
