-- Esquema inicial de NX Time, escrito a mano (no generado por Hibernate).
-- Sustituye al esquema que producía ddl-auto=update sobre SQLite, que no
-- tenía ni una sola clave foránea, ni un índice, ni una restricción de
-- unicidad real en la base de datos (todo vivía como comprobaciones en
-- código Java, es decir: como condiciones de carrera). Ver auditoría del
-- plan de profesionalización, Fase 3.

CREATE TABLE empresas (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(255) NOT NULL,
    version BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_empresas_nombre UNIQUE (nombre)
);

CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    nombre      VARCHAR(255) NOT NULL,
    contrasena  VARCHAR(255) NOT NULL,
    rol         VARCHAR(20)  NOT NULL,
    empresa_id  BIGINT       NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('EMPLEADO', 'GESTOR')),
    CONSTRAINT fk_usuarios_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresas (id) ON DELETE RESTRICT
);

CREATE INDEX idx_usuarios_empresa_rol ON usuarios (empresa_id, rol);

CREATE TABLE registros (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id                  BIGINT      NOT NULL,
    -- Denormalizado a propósito: hoy el tenant de un fichaje solo se
    -- alcanza navegando registros -> usuarios -> empresas. Tenerlo aquí
    -- directo permite filtrar e indexar por empresa sin ese salto, y es
    -- la base del filtrado multi-tenant sistemático.
    empresa_id                  BIGINT      NOT NULL,
    hora_entrada                TIMESTAMPTZ NOT NULL,
    hora_salida                 TIMESTAMPTZ,
    en_pausa                    BOOLEAN     NOT NULL DEFAULT FALSE,
    inicio_pausa_actual         TIMESTAMPTZ,
    segundos_pausa_acumulados   BIGINT      NOT NULL DEFAULT 0,
    version                     BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_registros_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_registros_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresas (id) ON DELETE RESTRICT
);

CREATE INDEX idx_registros_usuario_entrada ON registros (usuario_id, hora_entrada DESC);
CREATE INDEX idx_registros_empresa_entrada ON registros (empresa_id, hora_entrada DESC);

-- Garantiza a nivel de base de datos que un empleado no puede tener dos
-- jornadas abiertas a la vez. Antes esto solo lo comprobaba un `if` en
-- ServicioFichajeImpl: dos peticiones de fichar "INICIO" casi
-- simultáneas podían pasar ambas esa comprobación. Un índice único
-- parcial lo hace imposible, no solo improbable.
CREATE UNIQUE INDEX uq_registros_jornada_abierta ON registros (usuario_id) WHERE hora_salida IS NULL;

CREATE TABLE peticiones_ausencia (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT       NOT NULL,
    empresa_id    BIGINT       NOT NULL, -- denormalizado, ver registros.empresa_id
    fecha_inicio  DATE         NOT NULL,
    fecha_fin     DATE         NOT NULL,
    tipo          VARCHAR(30)  NOT NULL,
    estado        VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    motivo        VARCHAR(500),
    version       BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_peticiones_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_peticiones_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresas (id) ON DELETE RESTRICT,
    CONSTRAINT ck_peticiones_tipo CHECK (tipo IN (
        'VACACIONES', 'ASUNTOS_PROPIOS', 'MATRIMONIO', 'FALLECIMIENTO_FAMILIAR',
        'HOSPITALIZACION_FAMILIAR', 'LACTANCIA', 'MATERNIDAD_PATERNIDAD', 'MEDICO',
        'TRASLADO_DOMICILIO', 'VIAJE_TRABAJO', 'OTROS'
    )),
    CONSTRAINT ck_peticiones_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    CONSTRAINT ck_peticiones_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX idx_peticiones_empresa_estado ON peticiones_ausencia (empresa_id, estado);
CREATE INDEX idx_peticiones_usuario ON peticiones_ausencia (usuario_id);
