-- Borrado de datos personales (RGPD, art. 17). Ver ADR 016.
--
-- La tensión de fondo: el registro horario es de conservación obligatoria
-- 4 años (RD-ley 8/2019) y a una inspección un registro sin nombre no le
-- sirve de nada. Así que "bórrame" NO puede borrar fichajes. Se resuelve en
-- dos tiempos:
--
--  1. Al ejecutar la solicitud: se desactiva la cuenta y se borra lo que la
--     ley no obliga a conservar (CV, foto, fecha de nacimiento, avisos,
--     candidaturas, sesiones y códigos de acceso). Nombre, correo y fichajes
--     se quedan.
--  2. Cuatro años después del último fichaje: una tarea nocturna anonimiza
--     del todo a la persona y los textos libres que escribió.
--
-- La persona lo PIDE y RRHH/ADMIN lo EJECUTA: la empresa es la responsable
-- del tratamiento y tiene que poder comprobar que no queda nada abierto.

CREATE TABLE solicitudes_borrado (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id             BIGINT       NOT NULL,
    usuario_id             BIGINT       NOT NULL,

    estado                 VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',

    -- Opcional: el RGPD no obliga a dar razones para pedir el borrado.
    motivo                 TEXT,
    creada_en              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Quién la cerró y cuándo. En una CANCELADA es la propia persona.
    resuelta_por_id        BIGINT,
    resuelta_en            TIMESTAMPTZ,
    comentario_resolucion  TEXT,

    -- Solo en EJECUTADA: desde qué día la tarea nocturna puede anonimizar.
    anonimizar_desde       DATE,
    anonimizada_en         TIMESTAMPTZ,

    version                BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_borrados_empresa     FOREIGN KEY (empresa_id)      REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_borrados_usuario     FOREIGN KEY (usuario_id)      REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_borrados_resuelta_por FOREIGN KEY (resuelta_por_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    CONSTRAINT ck_borrados_estado
        CHECK (estado IN ('PENDIENTE', 'EJECUTADA', 'RECHAZADA', 'CANCELADA')),

    -- Cada estado con lo que le corresponde, sin excepciones. Es lo que
    -- habría que poder enseñar si alguien pregunta si se atendió su derecho.
    CONSTRAINT ck_borrados_coherente CHECK (
        (estado = 'PENDIENTE'
            AND resuelta_por_id IS NULL AND resuelta_en IS NULL
            AND anonimizar_desde IS NULL AND anonimizada_en IS NULL)
        OR
        (estado = 'EJECUTADA'
            AND resuelta_por_id IS NOT NULL AND resuelta_en IS NOT NULL
            AND anonimizar_desde IS NOT NULL)
        OR
        -- Rechazar sin decir por qué deja a la persona sin nada que hacer.
        (estado = 'RECHAZADA'
            AND resuelta_por_id IS NOT NULL AND resuelta_en IS NOT NULL
            AND comentario_resolucion IS NOT NULL
            AND anonimizar_desde IS NULL AND anonimizada_en IS NULL)
        OR
        (estado = 'CANCELADA'
            AND resuelta_por_id = usuario_id AND resuelta_en IS NOT NULL
            AND anonimizar_desde IS NULL AND anonimizada_en IS NULL)
    )
);

-- Una sola solicitud pendiente por persona. Parcial, como en las correcciones:
-- se puede volver a pedir después de una rechazada o cancelada.
CREATE UNIQUE INDEX uq_borrados_una_pendiente_por_usuario
    ON solicitudes_borrado (usuario_id)
    WHERE estado = 'PENDIENTE';

CREATE INDEX idx_borrados_empresa_estado ON solicitudes_borrado (empresa_id, estado);

-- Lo que busca cada noche la tarea de anonimización.
CREATE INDEX idx_borrados_por_anonimizar
    ON solicitudes_borrado (anonimizar_desde)
    WHERE estado = 'EJECUTADA' AND anonimizada_en IS NULL;

-- Sin DELETE: esta tabla es el registro de que un derecho se ejerció y se
-- atendió. Borrarla sería borrar la prueba.
GRANT SELECT, INSERT, UPDATE ON solicitudes_borrado TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ---------------------------------------------------------------------
-- Dos avisos nuevos
-- ---------------------------------------------------------------------
-- 🚨 El CHECK se reemplaza ENTERO: los catorce de V18 más los dos nuevos.
-- Listar de menos no falla al migrar, falla al insertar el aviso, dentro
-- del listener @Async y en silencio.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA',
    -- Fase H
    'OFERTA_PUBLICADA',
    'CANDIDATURA_RECIBIDA',
    'CANDIDATURA_ACTUALIZADA',
    -- 09/2026
    'RESUMEN_HORAS_EXTRA',
    -- 09/2026: borrado de datos (ADR 016)
    'BORRADO_SOLICITADO',
    'BORRADO_RECHAZADO'
));

-- ---------------------------------------------------------------------
-- La tarea nocturna de anonimización
-- ---------------------------------------------------------------------
-- 🚨 Mismo tipo de trampa que el CHECK de avisos: ejecuciones_tarea solo
-- admite las tareas listadas en V15. Sin ampliarlo, la tarea nueva fallaría
-- al registrar su propia ejecución, cada noche, y el monitor la daría por
-- no ejecutada sin que se viera por qué.
ALTER TABLE ejecuciones_tarea DROP CONSTRAINT ck_ejecuciones_tarea_tarea;
ALTER TABLE ejecuciones_tarea ADD CONSTRAINT ck_ejecuciones_tarea_tarea
    CHECK (tarea IN ('CIERRE_JORNADAS', 'HORAS_EXTRA', 'ANONIMIZACION'));
