-- Varios proyectos por persona e imputación de horas por jornada (ADR 017).
--
-- Hasta aquí una persona estaba en UN proyecto cada día, y sus horas se
-- deducían uniendo la jornada con esa asignación (ADR 009). Ahora puede estar
-- en varios a la vez, elegir en cuál trabaja al fichar y repartir el día. Así
-- que las horas dejan de deducirse y pasan a guardarse: cuántos segundos de
-- cada jornada van a cada proyecto.

-- ---------------------------------------------------------------------
-- 1. Asignaciones simultáneas
-- ---------------------------------------------------------------------
-- Se sustituye el EXCLUDE que impedía estar en dos proyectos el mismo día por
-- uno que solo impide estar DOS VECES en el mismo proyecto a la vez. Sigue en
-- la base por lo mismo que el original: comprobarlo en Java es leer y luego
-- escribir, una condición de carrera.
ALTER TABLE asignaciones_proyecto DROP CONSTRAINT ex_asignaciones_sin_solape;
ALTER TABLE asignaciones_proyecto ADD CONSTRAINT ex_asignaciones_sin_solape_mismo_proyecto
    EXCLUDE USING gist (
        usuario_id WITH =,
        proyecto_id WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'), '[]') WITH &&
    );

-- ---------------------------------------------------------------------
-- 2. Tramos: en qué proyecto se estaba trabajando y desde cuándo
-- ---------------------------------------------------------------------
-- Uno al iniciar la jornada y uno más cada vez que se pulsa "Cambiar de
-- proyecto". Son lo que pasó; las imputaciones de abajo son lo que cuenta.
--
-- segundos_pausa: las pausas FICHADAS con el botón durante el tramo (no se
-- puede cambiar de proyecto en pausa, así que cada pausa cae entera en uno).
-- Las pausas añadidas a posteriori no se suman aquí: tienen intervalo y se
-- reparten por solape al calcular.
CREATE TABLE tramos_proyecto (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,
    registro_id     BIGINT       NOT NULL,
    proyecto_id     BIGINT       NOT NULL,
    inicio          TIMESTAMPTZ  NOT NULL,
    fin             TIMESTAMPTZ,
    segundos_pausa  BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_tramos_empresa  FOREIGN KEY (empresa_id)  REFERENCES empresas(id)  ON DELETE RESTRICT,
    CONSTRAINT fk_tramos_registro FOREIGN KEY (registro_id) REFERENCES registros(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tramos_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tramos_fechas CHECK (fin IS NULL OR fin >= inicio),
    CONSTRAINT ck_tramos_pausa CHECK (segundos_pausa >= 0)
);

-- Un solo tramo abierto por jornada: cambiar de proyecto cierra el anterior.
CREATE UNIQUE INDEX uq_tramos_uno_abierto_por_registro ON tramos_proyecto (registro_id) WHERE fin IS NULL;
CREATE INDEX idx_tramos_registro ON tramos_proyecto (registro_id);

-- Sin DELETE: lo que se hizo no se borra. Se re-apuntan al corregir.
GRANT SELECT, INSERT, UPDATE ON tramos_proyecto TO nxtime_app;

-- ---------------------------------------------------------------------
-- 3. Imputaciones: cuánto de cada jornada va a cada proyecto
-- ---------------------------------------------------------------------
-- Es lo que leen los informes. Invariante (la mantiene el servicio, que es
-- quien sabe el neto): en una jornada cerrada con imputaciones, la suma de
-- segundos es el neto de la jornada.
--
-- origen: TRAMOS si salió de los tramos y se recalcula si cambian las pausas;
-- MANUAL si alguien repartió a mano (o una corrección cambió las horas), y
-- entonces se reescala en proporción.
CREATE TABLE imputaciones_proyecto (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,
    registro_id     BIGINT       NOT NULL,
    proyecto_id     BIGINT       NOT NULL,
    segundos        BIGINT       NOT NULL,
    origen          VARCHAR(10)  NOT NULL,
    actualizada_en  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_imputaciones_empresa  FOREIGN KEY (empresa_id)  REFERENCES empresas(id)  ON DELETE RESTRICT,
    CONSTRAINT fk_imputaciones_registro FOREIGN KEY (registro_id) REFERENCES registros(id) ON DELETE RESTRICT,
    CONSTRAINT fk_imputaciones_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE RESTRICT,
    CONSTRAINT uq_imputaciones_registro_proyecto UNIQUE (registro_id, proyecto_id),
    CONSTRAINT ck_imputaciones_segundos CHECK (segundos >= 0),
    CONSTRAINT ck_imputaciones_origen CHECK (origen IN ('TRAMOS', 'MANUAL'))
);

CREATE INDEX idx_imputaciones_proyecto ON imputaciones_proyecto (proyecto_id);
CREATE INDEX idx_imputaciones_empresa ON imputaciones_proyecto (empresa_id);

-- Con DELETE: repartir de nuevo sustituye las filas de la jornada. La traza
-- de cada reparto queda en auditoria_fichaje, que es append-only.
GRANT SELECT, INSERT, UPDATE, DELETE ON imputaciones_proyecto TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ---------------------------------------------------------------------
-- 4. Las horas ya fichadas no pueden desaparecer de los informes
-- ---------------------------------------------------------------------
-- Una imputación por cada jornada cerrada y viva con asignación vigente ese
-- día (en hora de España), con TODO su neto: exactamente lo que la consulta
-- anterior deducía. Hasta esta migración el EXCLUDE garantizaba una sola
-- asignación por persona y día, así que no puede salir ninguna duplicada.
--
-- GREATEST(…, 0): una jornada con más pausa que duración (solo posible tras
-- una edición a mano de la base) contaba antes en negativo; aquí cuenta cero,
-- que es lo que el CHECK admite.
INSERT INTO imputaciones_proyecto (empresa_id, registro_id, proyecto_id, segundos, origen)
SELECT r.empresa_id,
       r.id,
       a.proyecto_id,
       GREATEST(EXTRACT(EPOCH FROM (r.hora_salida - r.hora_entrada))::BIGINT - r.segundos_pausa_acumulados, 0),
       'TRAMOS'
FROM registros r
JOIN asignaciones_proyecto a
  ON a.usuario_id = r.usuario_id
 AND (r.hora_entrada AT TIME ZONE 'Europe/Madrid')::date >= a.fecha_inicio
 AND (r.hora_entrada AT TIME ZONE 'Europe/Madrid')::date <= COALESCE(a.fecha_fin, DATE 'infinity')
WHERE r.anulado = false
  AND r.hora_salida IS NOT NULL;
