-- Repartir a mano las horas de una jornada entre proyectos (ADR 017).
--
-- Dentro de la semana en curso, la propia persona lo aplica. De semanas
-- anteriores, se pide y lo aprueba un gestor por el circuito que ya existe
-- (solicitudes_correccion): un mes ya informado no cambia de reparto sin que
-- nadie lo mire.

-- El reparto que se propone en una solicitud de corrección. Tabla y no JSONB:
-- cada línea apunta a un proyecto de verdad, con su clave ajena, y así no se
-- puede proponer un reparto a un proyecto que ya no existe.
CREATE TABLE repartos_propuestos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id BIGINT NOT NULL,
    proyecto_id  BIGINT NOT NULL,
    segundos     BIGINT NOT NULL,

    CONSTRAINT fk_repartos_solicitud FOREIGN KEY (solicitud_id)
        REFERENCES solicitudes_correccion(id) ON DELETE CASCADE,
    CONSTRAINT fk_repartos_proyecto FOREIGN KEY (proyecto_id)
        REFERENCES proyectos(id) ON DELETE RESTRICT,
    CONSTRAINT uq_repartos_solicitud_proyecto UNIQUE (solicitud_id, proyecto_id),
    CONSTRAINT ck_repartos_segundos CHECK (segundos >= 0)
);

CREATE INDEX idx_repartos_solicitud ON repartos_propuestos (solicitud_id);

-- ON DELETE CASCADE arriba y DELETE aquí: las líneas son parte de la
-- solicitud, no un registro propio. Una solicitud no se borra nunca, pero
-- rehacer el reparto antes de enviarla sí sustituye sus líneas.
GRANT SELECT, INSERT, UPDATE, DELETE ON repartos_propuestos TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ---------------------------------------------------------------------
-- La auditoría gana una acción
-- ---------------------------------------------------------------------
-- 🚨 El CHECK se reemplaza ENTERO: las diez de V24 más la nueva.
ALTER TABLE auditoria_fichaje DROP CONSTRAINT auditoria_fichaje_accion_check;
ALTER TABLE auditoria_fichaje ADD CONSTRAINT auditoria_fichaje_accion_check
    CHECK (accion IN (
        'CREACION',
        'MODIFICACION',
        'CORRECCION',
        'ANULACION',
        'SOLICITUD_CORRECCION',
        'RECHAZO_CORRECCION',
        'DISPUTA',
        'PAUSA_ANADIDA',
        'PAUSA_ANULADA',
        'PROYECTO_CAMBIADO',
        'REPARTO_PROYECTOS'
    ));
