-- Puntos de control de la cadena de auditoría (Fase A4).
--
-- Verificar la traza era una operación de todo o nada: se leían TODAS las
-- filas de la tabla, de todas las empresas, con sus dos columnas JSONB, y se
-- recorrían en memoria. El registro se conserva cuatro años por ley y crece con
-- cada fichaje, cada pausa y cada corrección, así que esa consulta solo podía
-- ir a peor. Y como cuesta, se pide poco; y como se pide poco, una manipulación
-- podía tardar meses en salir a la luz.
--
-- Un punto de control dice "hasta la fila N la cadena estaba intacta, y el hash
-- de la fila N era H". Con eso, la verificación de cada noche solo tiene que
-- mirar lo que se ha escrito desde entonces, que son unas pocas filas.
--
-- Las cifras acumuladas (filas, comprobadas, solo_enlace) se guardan para que
-- una verificación incremental siga pudiendo dar los totales de la traza
-- entera sin volver a recorrerla.

CREATE TABLE puntos_control_auditoria (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Hasta qué fila de auditoria_fichaje llegó esta comprobación.
    hasta_id      BIGINT      NOT NULL,
    -- El hash de esa fila: es con lo que enlaza la siguiente, y sin él la
    -- verificación incremental no podría comprobar el primer eslabón.
    -- VARCHAR(64) y no CHAR(64) para que case con auditoria_fichaje.hash: con
    -- CHAR, PostgreSQL lo declara bpchar y la validación de esquema de
    -- Hibernate (ddl-auto: validate) rechaza el arranque.
    hash          VARCHAR(64) NOT NULL,
    -- Totales acumulados desde el principio de la traza.
    filas         BIGINT      NOT NULL CHECK (filas >= 0),
    comprobadas   BIGINT      NOT NULL CHECK (comprobadas >= 0),
    solo_enlace   BIGINT      NOT NULL CHECK (solo_enlace >= 0),
    verificado_en TIMESTAMPTZ NOT NULL,

    -- Un punto de control por fila: reverificar no crea uno nuevo si no ha
    -- avanzado nada.
    CONSTRAINT uq_punto_control_hasta UNIQUE (hasta_id),
    -- Las dos clases de fila tienen que sumar el total; si no, el punto de
    -- control estaría contando mal y nadie se enteraría.
    CONSTRAINT ck_punto_control_cifras CHECK (comprobadas + solo_enlace = filas)
);

COMMENT ON TABLE puntos_control_auditoria IS
    'Hasta dónde se ha comprobado la cadena de auditoría y con qué resultado. Ver VerificadorDeAuditoria.';

-- Sin UPDATE ni DELETE, por el mismo motivo que auditoria_fichaje: un punto de
-- control que se puede reescribir no sirve para demostrar nada. El GRANT es
-- explícito porque el ALTER DEFAULT PRIVILEGES de V3 concede los cuatro
-- permisos, y aquí solo queremos dos.
REVOKE UPDATE, DELETE ON puntos_control_auditoria FROM nxtime_app;
GRANT SELECT, INSERT ON puntos_control_auditoria TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- La verificación pasa a correr sola cada noche: que la integridad sea
-- demostrable no puede depender de que alguien se acuerde de pulsar un botón.
--
-- 🚨 ejecuciones_tarea solo admite las tareas listadas en su CHECK, y hay que
-- REEMPLAZARLO ENTERO (mismo patrón que V20): sin esto la tarea fallaría al
-- registrar su propia ejecución, cada noche, y el monitor la daría por no
-- ejecutada sin que se viera por qué.
ALTER TABLE ejecuciones_tarea DROP CONSTRAINT ck_ejecuciones_tarea_tarea;
ALTER TABLE ejecuciones_tarea ADD CONSTRAINT ck_ejecuciones_tarea_tarea
    CHECK (tarea IN ('CIERRE_JORNADAS', 'HORAS_EXTRA', 'ANONIMIZACION',
                     'VERIFICACION_INTEGRIDAD'));
