-- Fase 4 (seguridad reforzada): refresh tokens, roles RRHH/ADMIN, baja
-- de usuarios. Ver la auditoría del plan de profesionalización.

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255)  NOT NULL,
    usuario_id  BIGINT        NOT NULL,
    expira_en   TIMESTAMPTZ   NOT NULL,
    revocado    BOOLEAN       NOT NULL DEFAULT FALSE,
    creado_en   TIMESTAMPTZ   NOT NULL,

    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE CASCADE
);

-- ON DELETE CASCADE aquí (no RESTRICT como en el resto del esquema): un
-- refresh token no tiene valor de trazabilidad legal como un fichaje o
-- una ausencia -- si el usuario se borrase, sus sesiones vivas deben
-- desaparecer con él, no bloquear el borrado.

CREATE INDEX idx_refresh_tokens_usuario ON refresh_tokens (usuario_id);

-- Amplía el CHECK de rol para admitir los dos roles nuevos.
ALTER TABLE usuarios DROP CONSTRAINT ck_usuarios_rol;
ALTER TABLE usuarios ADD CONSTRAINT ck_usuarios_rol
    CHECK (rol IN ('EMPLEADO', 'GESTOR', 'RRHH', 'ADMIN'));

-- Baja de usuarios: antes los flags de cuenta de UserDetails estaban
-- cableados a true sin excepción (ver auditoría) -- no se podía dar de
-- baja a nadie. Los fichajes y ausencias de un usuario dado de baja NO
-- se tocan (requisito legal de trazabilidad).
ALTER TABLE usuarios ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE usuarios ADD COLUMN fecha_baja TIMESTAMPTZ;
