-- Fase B1 (plan de septiembre de 2026): cuadrantes y horario teórico.
--
-- A qué hora debía trabajar cada persona cada día. Hasta ahora el sistema
-- solo sabía CUÁNTO (usuarios.horas_semanales, la jornada contratada), no
-- CUÁNDO. Esto no sustituye a horas_semanales: lo complementa. Ver ADR 023.
--
-- Tres decisiones de modelado, que son las que condicionan todo lo demás:
--
--  1. PLANTILLA SEMANAL REUTILIZABLE + EXCEPCIONES POR DÍA. Una empresa tiene
--     tres o cuatro horarios ("oficina", "turno de mañana", "intensiva de
--     verano"), no uno por persona.
--
--  2. VIGENCIA, exactamente como asignaciones_proyecto (V10, ADR 009): un
--     cuadrante que cambia en marzo NO puede reescribir febrero, porque
--     febrero ya está informado y auditado.
--
--  3. MINUTOS DESDE MEDIANOCHE, no TIME. Un turno de noche de 22:00 a 06:00
--     es inicio 1320, fin 1800: una sola fila, sin partirlo en dos. Con TIME
--     el fin sería MENOR que el inicio y no habría forma de escribir ni el
--     CHECK ni el solape. Y los minutos son nominales -- el turno de la noche
--     del cambio de hora cuenta 8 h, como todas las demás --, que es lo que
--     se quiere de un horario TEÓRICO.

-- ---------------------------------------------------------------------
-- Plantillas
-- ---------------------------------------------------------------------
CREATE TABLE plantillas_horario (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  BIGINT       NOT NULL,
    nombre      VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    version     BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_plantillas_horario_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT uq_plantillas_horario_empresa_nombre UNIQUE (empresa_id, nombre)
);

-- ---------------------------------------------------------------------
-- Tramos de una plantilla
-- ---------------------------------------------------------------------
-- Un tramo pertenece al día en el que EMPIEZA. dia_semana es ISO (1 = lunes,
-- 7 = domingo), el mismo que java.time.DayOfWeek.getValue(), para que no
-- haya una traducción que equivocar.
--
-- Un día sin tramos es un día libre en esa plantilla. Una jornada partida
-- son dos tramos del mismo día.
CREATE TABLE tramos_plantilla_horario (
    id           BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantilla_id BIGINT   NOT NULL,
    dia_semana   SMALLINT NOT NULL,
    inicio       INTEGER  NOT NULL,
    fin          INTEGER  NOT NULL,

    CONSTRAINT fk_tramos_plantilla
        FOREIGN KEY (plantilla_id) REFERENCES plantillas_horario(id) ON DELETE CASCADE,
    CONSTRAINT ck_tramos_dia_semana CHECK (dia_semana BETWEEN 1 AND 7),
    -- Empieza dentro de su día, termina después de empezar, y dura como
    -- mucho 24 h. El fin puede pasar de 1440: es el turno que cruza la
    -- medianoche.
    CONSTRAINT ck_tramos_minutos CHECK (
        inicio >= 0 AND inicio < 1440
        AND fin > inicio
        AND fin - inicio <= 1440
    ),

    -- Dos tramos del mismo día no se pisan. En la base y no en Java por el
    -- motivo de siempre (V10): comprobarlo en código es leer y luego
    -- escribir. int4range es semiabierto [inicio, fin), así que un tramo que
    -- acaba a las 14:00 y otro que empieza a las 14:00 NO chocan.
    --
    -- Lo que esto NO ve es el solape entre días: un turno del lunes de 22:00
    -- a 06:00 pisa un tramo del martes que empiece a las 05:00. Eso lo
    -- comprueba ReglasDeCuadrante al guardar la plantilla; aquí no se puede
    -- expresar sin reescribir los tramos a minutos de la semana.
    CONSTRAINT ex_tramos_sin_solape EXCLUDE USING gist (
        plantilla_id WITH =,
        dia_semana WITH =,
        int4range(inicio, fin) WITH &&
    )
);

-- ---------------------------------------------------------------------
-- Asignaciones de plantilla a persona, con vigencia
-- ---------------------------------------------------------------------
-- Calcada de asignaciones_proyecto (V10). fecha_fin NULL = sigue vigente.
CREATE TABLE asignaciones_horario (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id   BIGINT NOT NULL,
    usuario_id   BIGINT NOT NULL,
    plantilla_id BIGINT NOT NULL,
    fecha_inicio DATE   NOT NULL,
    fecha_fin    DATE,
    version      BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_asignaciones_horario_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asignaciones_horario_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    -- RESTRICT: una plantilla que alguien ha tenido asignada no se puede
    -- borrar, porque explica las horas teóricas de esos días.
    CONSTRAINT fk_asignaciones_horario_plantilla
        FOREIGN KEY (plantilla_id) REFERENCES plantillas_horario(id) ON DELETE RESTRICT,
    CONSTRAINT ck_asignaciones_horario_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),

    -- Un solo cuadrante por persona y día. Mismo EXCLUDE que V10, con el
    -- mismo '[]' y la misma normalización: una que termina el 30/6 y otra
    -- que empieza el 1/7 no se solapan.
    CONSTRAINT ex_asignaciones_horario_sin_solape EXCLUDE USING gist (
        usuario_id WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'), '[]') WITH &&
    )
);

CREATE INDEX idx_asignaciones_horario_plantilla ON asignaciones_horario (plantilla_id);
CREATE INDEX idx_asignaciones_horario_empresa ON asignaciones_horario (empresa_id);

-- ---------------------------------------------------------------------
-- Excepciones de un día concreto
-- ---------------------------------------------------------------------
-- Mandan sobre la plantilla ese día. Dos tipos:
--   LIBRE -> ese día no se trabaja (un día cambiado, un permiso pactado).
--            Una fila, sin horas.
--   TRAMO -> ese día se trabaja en este tramo EN LUGAR de lo que diga la
--            plantilla. Una fila por tramo: una jornada partida son dos.
--
-- Los festivos y las ausencias aprobadas NO van aquí: ya los resuelve
-- NonWorkingDayService, y copiarlos sería tener dos verdades.
CREATE TABLE excepciones_horario (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT       NOT NULL,
    usuario_id BIGINT       NOT NULL,
    fecha      DATE         NOT NULL,
    tipo       VARCHAR(10)  NOT NULL,
    inicio     INTEGER,
    fin        INTEGER,
    motivo     VARCHAR(300),
    creada_por_id BIGINT,

    CONSTRAINT fk_excepciones_horario_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_excepciones_horario_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_excepciones_horario_creada_por
        FOREIGN KEY (creada_por_id) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT ck_excepciones_horario_tipo CHECK (tipo IN ('LIBRE', 'TRAMO')),
    -- Coherencia entre el tipo y las horas: un LIBRE no tiene horas, un
    -- TRAMO tiene las dos y con las mismas reglas que un tramo de plantilla.
    CONSTRAINT ck_excepciones_horario_coherencia CHECK (
        (tipo = 'LIBRE' AND inicio IS NULL AND fin IS NULL)
        OR (tipo = 'TRAMO' AND inicio IS NOT NULL AND fin IS NOT NULL
            AND inicio >= 0 AND inicio < 1440
            AND fin > inicio AND fin - inicio <= 1440)
    ),

    -- Una sola restricción cubre los dos choques posibles:
    --  - dos tramos del mismo día que se pisan;
    --  - un LIBRE junto a cualquier tramo del mismo día. El LIBRE ocupa el
    --    día entero ([0, 2880), que abarca también el turno más largo que
    --    pueda empezar ese día), así que choca con todo.
    CONSTRAINT ex_excepciones_horario_sin_solape EXCLUDE USING gist (
        usuario_id WITH =,
        fecha WITH =,
        int4range(COALESCE(inicio, 0), COALESCE(fin, 2880)) WITH &&
    )
);

CREATE INDEX idx_excepciones_horario_empresa ON excepciones_horario (empresa_id);

GRANT SELECT, INSERT, UPDATE, DELETE
    ON plantillas_horario, tramos_plantilla_horario, asignaciones_horario, excepciones_horario
    TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ---------------------------------------------------------------------
-- El aviso de "este cuadrante no cuadra con la jornada contratada"
-- ---------------------------------------------------------------------
-- 🚨 El CHECK se reemplaza ENTERO: los diecisiete de V22 más el nuevo.
-- Listar de menos no falla al migrar, falla al insertar el aviso, dentro del
-- listener @Async y en silencio.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA',
    -- Fase H
    'OFERTA_PUBLICADA',
    'CANDIDATURA_RECIBIDA',
    'CANDIDATURA_ACTUALIZADA',
    -- 09/2026
    'RESUMEN_HORAS_EXTRA',
    -- 09/2026: borrado de datos (ADR 016)
    'BORRADO_SOLICITADO',
    'BORRADO_RECHAZADO',
    -- 09/2026: trabajar en festivo o con una ausencia aprobada
    'TRABAJO_EN_DIA_NO_LABORABLE',
    -- B1: un cuadrante asignado que no suma la jornada contratada
    'CUADRANTE_DISTINTO_DE_JORNADA'
));
