-- Fase B2 (plan de septiembre de 2026): incidencias de cuadrante.
--
-- Retrasos, salidas anticipadas y ausencias no justificadas, comparando cada
-- día lo fichado con el horario teórico (V31, JornadaTeoricaService).
--
-- Rima con el ADR 011 de las horas extra: SE DETECTA, NO SE IMPUTA. Una
-- incidencia no descuenta nada de nadie. Nace PENDIENTE, quien la tiene puede
-- explicarla y quien revisa decide si la explicación vale. Es un registro de
-- que algo no cuadró, no una sanción.

CREATE TABLE incidencias_cuadrante (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  BIGINT      NOT NULL,
    usuario_id  BIGINT      NOT NULL,
    fecha       DATE        NOT NULL,
    tipo        VARCHAR(20) NOT NULL,

    -- Cuánto: minutos de retraso, minutos antes de la hora de salida, o los
    -- minutos teóricos del día en una ausencia.
    minutos     INTEGER     NOT NULL,

    -- Contra qué se comparó: la hora teórica, en minutos desde la medianoche
    -- de "fecha", como en los tramos (puede pasar de 1440 en un turno de
    -- noche). Sin esto, "25 minutos tarde" no dice tarde respecto a qué.
    hora_prevista INTEGER   NOT NULL,

    -- Lo que pasó: la entrada real en un retraso, la salida real en una
    -- salida anticipada. Null en una ausencia: no hay nada que enseñar.
    hora_real   TIMESTAMPTZ,
    registro_id BIGINT,

    estado      VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    justificacion         VARCHAR(1000),
    justificada_en        TIMESTAMPTZ,
    comentario_resolucion VARCHAR(1000),
    resuelta_por_id       BIGINT,
    resuelta_en           TIMESTAMPTZ,
    detectada_en          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version     BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fk_incidencias_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_incidencias_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    -- SET NULL: si el fichaje se anula por una corrección, la incidencia no
    -- tiene por qué desaparecer con él; el barrido siguiente decide si sigue
    -- procediendo.
    CONSTRAINT fk_incidencias_registro
        FOREIGN KEY (registro_id) REFERENCES registros(id) ON DELETE SET NULL,
    CONSTRAINT fk_incidencias_resuelta_por
        FOREIGN KEY (resuelta_por_id) REFERENCES usuarios(id) ON DELETE SET NULL,

    CONSTRAINT ck_incidencias_tipo CHECK (tipo IN ('RETRASO', 'SALIDA_ANTICIPADA', 'AUSENCIA')),
    CONSTRAINT ck_incidencias_estado CHECK (estado IN ('PENDIENTE', 'JUSTIFICADA', 'ACEPTADA', 'RECHAZADA')),
    CONSTRAINT ck_incidencias_minutos CHECK (minutos > 0),
    -- Una resuelta dice quién y cuándo; una sin resolver, no.
    CONSTRAINT ck_incidencias_resolucion CHECK (
        (estado IN ('ACEPTADA', 'RECHAZADA')) = (resuelta_en IS NOT NULL)
    ),

    -- La idempotencia del barrido, en la base. El barrido mira catorce días
    -- hacia atrás cada noche --por las correcciones, como el de horas extra--,
    -- así que pasa varias veces por el mismo día. Correrlo dos veces no puede
    -- duplicar nada, y eso no se deja a la disciplina del código.
    CONSTRAINT uq_incidencias_usuario_fecha_tipo UNIQUE (usuario_id, fecha, tipo)
);

CREATE INDEX idx_incidencias_empresa_estado ON incidencias_cuadrante (empresa_id, estado);
CREATE INDEX idx_incidencias_fecha ON incidencias_cuadrante (fecha);

GRANT SELECT, INSERT, UPDATE, DELETE ON incidencias_cuadrante TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ---------------------------------------------------------------------
-- La tarea nocturna
-- ---------------------------------------------------------------------
-- 🚨 Se reemplaza ENTERO: los cuatro de V28 más el nuevo.
ALTER TABLE ejecuciones_tarea DROP CONSTRAINT ck_ejecuciones_tarea_tarea;
ALTER TABLE ejecuciones_tarea ADD CONSTRAINT ck_ejecuciones_tarea_tarea
    CHECK (tarea IN ('CIERRE_JORNADAS', 'HORAS_EXTRA', 'ANONIMIZACION',
                     'VERIFICACION_INTEGRIDAD', 'CUMPLIMIENTO_CUADRANTE'));

-- ---------------------------------------------------------------------
-- Los dos avisos
-- ---------------------------------------------------------------------
-- 🚨 Se reemplaza ENTERO: los dieciocho de V31 más los dos nuevos. Listar de
-- menos no falla al migrar, falla al insertar el aviso, dentro del listener
-- @Async y en silencio.
ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA',
    -- Fase H
    'OFERTA_PUBLICADA',
    'CANDIDATURA_RECIBIDA',
    'CANDIDATURA_ACTUALIZADA',
    -- 09/2026
    'RESUMEN_HORAS_EXTRA',
    -- 09/2026: borrado de datos (ADR 016)
    'BORRADO_SOLICITADO',
    'BORRADO_RECHAZADO',
    -- 09/2026: trabajar en festivo o con una ausencia aprobada
    'TRABAJO_EN_DIA_NO_LABORABLE',
    -- B1: un cuadrante asignado que no suma la jornada contratada
    'CUADRANTE_DISTINTO_DE_JORNADA',
    -- B2: la incidencia, a quien la tiene; el resumen, a quien revisa
    'INCIDENCIA_DETECTADA',
    'RESUMEN_INCIDENCIAS'
));
