-- ============================================================================
-- Fase B3: la firma mensual del registro horario (ADR 025).
--
-- La persona firma, una vez terminado el mes, que su registro de ese mes es
-- correcto. Es una firma de ACEPTACIÓN, no una firma electrónica cualificada
-- eIDAS: lo que se guarda es el SHA-256 de un resumen canónico del mes (ver
-- HuellaDelMes), para poder demostrar después qué se firmó.
--
-- Tabla aparte y no dentro de auditoria_fichaje, por tres razones:
--   * auditoria_fichaje es append-only (trigger + REVOKE UPDATE), y una firma
--     tiene que poder pasar a INVALIDADA;
--   * su cadena es global a todas las empresas: verificar una firma no puede
--     obligar a recorrerla entera;
--   * lo que se firma no es una fila de auditoría sino un resumen del mes.
--
-- La firma NO bloquea la corrección: la corrección invalida la firma, en la
-- misma transacción (SignatureInvalidationListener). Bloquear sería ilegal
-- --el RD-ley 8/2019 exige que el registro sea veraz-- y perverso: nadie
-- firmaría.
-- ============================================================================

CREATE TABLE firmas_mensuales (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT      NOT NULL,
    usuario_id      BIGINT      NOT NULL,
    anio            INTEGER     NOT NULL,
    mes             INTEGER     NOT NULL,
    -- SHA-256 en hexadecimal del resumen canónico del mes. VARCHAR y no
    -- CHAR, como en V13 y V28: la validación de esquema de Hibernate no casa
    -- un CHAR con un String. La longitud la garantiza el CHECK de abajo.
    hash            VARCHAR(64) NOT NULL,
    -- Qué definición de "resumen del mes" se firmó. Si algún día cambia, las
    -- firmas viejas se siguen verificando con la suya.
    version_huella  SMALLINT    NOT NULL,
    -- Cuántas jornadas y cuántos segundos netos se firmaron: se enseñan sin
    -- tener que recalcular, y dicen de un vistazo qué cambió al invalidarse.
    jornadas        INTEGER     NOT NULL,
    segundos_netos  BIGINT      NOT NULL,
    estado          VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    firmada_en      TIMESTAMPTZ NOT NULL,
    ip              VARCHAR(45),
    invalidada_en   TIMESTAMPTZ,
    motivo_invalidacion VARCHAR(300),
    -- El visado de la empresa (firma:visar, RRHH). Opcional: la firma del
    -- trabajador vale sin él.
    visada_por_id   BIGINT,
    visada_en       TIMESTAMPTZ,
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_firmas_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_firmas_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_firmas_visada_por
        FOREIGN KEY (visada_por_id) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT ck_firmas_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_firmas_hash CHECK (char_length(hash) = 64),
    CONSTRAINT ck_firmas_estado CHECK (estado IN ('VIGENTE', 'INVALIDADA')),
    -- Una invalidada dice cuándo; una vigente, no.
    CONSTRAINT ck_firmas_invalidacion CHECK ((estado = 'INVALIDADA') = (invalidada_en IS NOT NULL)),
    CONSTRAINT ck_firmas_visado CHECK ((visada_por_id IS NULL) OR (visada_en IS NOT NULL))
);

-- Una sola firma VIGENTE por persona y mes, pero las invalidadas se quedan:
-- son el histórico de qué se firmó y qué lo tumbó. Índice PARCIAL, el mismo
-- truco que uq_registros_jornada_abierta.
CREATE UNIQUE INDEX uq_firmas_vigente ON firmas_mensuales (usuario_id, anio, mes)
    WHERE estado = 'VIGENTE';

CREATE INDEX idx_firmas_empresa_mes ON firmas_mensuales (empresa_id, anio, mes);

-- Sin DELETE: una firma no se borra, se invalida.
GRANT SELECT, INSERT, UPDATE ON firmas_mensuales TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- ----------------------------------------------------------------------------
-- La tarea del recordatorio. Diaria y no mensual, a propósito: si el día 1
-- Render estaba dormido, el día 2 se pone al día (y el vigilante de
-- /estado/tareas solo sabe de tareas que corren al menos cada 48 horas).
-- Lista entera, como en V20 y V32.
-- ----------------------------------------------------------------------------
ALTER TABLE ejecuciones_tarea DROP CONSTRAINT ck_ejecuciones_tarea_tarea;
ALTER TABLE ejecuciones_tarea ADD CONSTRAINT ck_ejecuciones_tarea_tarea
    CHECK (tarea IN ('CIERRE_JORNADAS', 'HORAS_EXTRA', 'ANONIMIZACION',
                     'VERIFICACION_INTEGRIDAD', 'CUMPLIMIENTO_CUADRANTE',
                     'RECORDATORIO_FIRMA'));

ALTER TABLE avisos DROP CONSTRAINT ck_avisos_tipo;
ALTER TABLE avisos ADD CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
    -- Fase A
    'AUSENCIA_SOLICITADA',
    'AUSENCIA_RESUELTA',
    'BIENVENIDA',
    -- Fase E
    'CORRECCION_SOLICITADA',
    'CORRECCION_RESUELTA',
    'CORRECCION_EN_DISPUTA',
    -- Fase F
    'HORAS_EXTRA_DETECTADAS',
    'BOLSA_HORAS_EXTRA_AL_LIMITE',
    -- Fase G
    'DENUNCIA_RECIBIDA',
    'DENUNCIA_ACTUALIZADA',
    -- Fase H
    'OFERTA_PUBLICADA',
    'CANDIDATURA_RECIBIDA',
    'CANDIDATURA_ACTUALIZADA',
    -- 09/2026
    'RESUMEN_HORAS_EXTRA',
    -- 09/2026: borrado de datos (ADR 016)
    'BORRADO_SOLICITADO',
    'BORRADO_RECHAZADO',
    -- 09/2026: trabajar en festivo o con una ausencia aprobada
    'TRABAJO_EN_DIA_NO_LABORABLE',
    -- B1: un cuadrante asignado que no suma la jornada contratada
    'CUADRANTE_DISTINTO_DE_JORNADA',
    -- B2: la incidencia, a quien la tiene; el resumen, a quien revisa
    'INCIDENCIA_DETECTADA',
    'RESUMEN_INCIDENCIAS',
    -- B3: el mes que se puede firmar, y la firma que una corrección tumbó
    'RECORDATORIO_FIRMA',
    'FIRMA_INVALIDADA'
));
