-- Fase B5 (plan de septiembre de 2026): notificaciones push con FCM.
--
-- Un móvil (o, algún día, un navegador) al que se le pueden mandar avisos.
-- Es lo único que el servidor necesita saber: el token que FCM le dio a esa
-- instalación de la app.
--
-- El token es dato personal: identifica un dispositivo de una persona. Se
-- borra al ejecutar un borrado de datos (PersonalDataEraser), sale en la
-- exportación de datos, y se borra también en cuanto FCM dice que ya no vale.

CREATE TABLE dispositivos_push (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,

    -- WEB e IOS desde el día uno aunque hoy solo haya app Android: es lo que
    -- deja Web Push preparado sin implementarlo (ADR 028).
    plataforma  VARCHAR(10)  NOT NULL,

    -- Los tokens de FCM rondan los 160 caracteres, pero Google no promete un
    -- tamaño: margen de sobra.
    token       VARCHAR(4096) NOT NULL,

    registrado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Se renueva cada vez que la app vuelve a registrar el token (al entrar).
    -- Sirve para ver si un dispositivo lleva meses sin usarse.
    visto_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_dispositivos_push_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT ck_dispositivos_push_plataforma CHECK (plataforma IN ('ANDROID', 'WEB', 'IOS')),

    -- Un token es de UNA instalación, y por tanto de una sola persona a la
    -- vez. En un móvil compartido, cuando entra otra persona el token cambia
    -- de dueño (ver PushDeviceServiceImpl.registrar): sin esta unicidad, el
    -- mismo móvil recibiría los avisos de las dos.
    CONSTRAINT uq_dispositivos_push_token UNIQUE (token)
);

CREATE INDEX idx_dispositivos_push_usuario ON dispositivos_push (usuario_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON dispositivos_push TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
