-- Plan del 30/09/2026, fase K1: fichar en un kiosco (ADR 033).
--
-- Un kiosco es una tablet en la entrada de un centro de trabajo donde la
-- plantilla ficha sin abrir su propia sesión: pasa su tarjeta QR por la cámara
-- o, si no la lleva, busca su nombre y teclea su PIN.

-- El kiosco es un DISPOSITIVO de una empresa, no una persona. Se identifica con
-- un token opaco del que solo se guarda el SHA-256, como los refresh tokens
-- (ADR 019). No se borra nunca: los fichajes que se hicieron en él lo citan.
-- Se revoca.
CREATE TABLE kioscos (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id   BIGINT       NOT NULL,
    nombre       VARCHAR(80)  NOT NULL,
    token_hash   VARCHAR(64),
    creado_por   BIGINT,
    creado_en    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    ultimo_uso   TIMESTAMPTZ,
    revocado_en  TIMESTAMPTZ,

    CONSTRAINT fk_kioscos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_kioscos_creado_por FOREIGN KEY (creado_por) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT uq_kioscos_token UNIQUE (token_hash)
);

CREATE INDEX idx_kioscos_empresa ON kioscos (empresa_id);

-- Emparejar una tablet: la tablet pide un código corto y lo enseña; el ADMIN lo
-- teclea en los ajustes de la empresa. La tablet pregunta por el estado con un
-- secreto que solo ella tiene, y el token del kiosco se genera y se le entrega
-- UNA vez, en esa respuesta. De los dos, código y secreto, solo se guarda el
-- hash. Caducan a los diez minutos.
CREATE TABLE kiosco_emparejamientos (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_hash   VARCHAR(64)  NOT NULL,
    secreto_hash  VARCHAR(64)  NOT NULL,
    kiosco_id     BIGINT,
    caduca_en     TIMESTAMPTZ  NOT NULL,
    entregado_en  TIMESTAMPTZ,

    CONSTRAINT fk_kiosco_emparejamientos_kiosco FOREIGN KEY (kiosco_id) REFERENCES kioscos(id),
    CONSTRAINT uq_kiosco_emparejamientos_secreto UNIQUE (secreto_hash)
);

CREATE INDEX idx_kiosco_emparejamientos_codigo ON kiosco_emparejamientos (codigo_hash);

-- Cómo se identifica cada persona en el kiosco.
--  - El PIN lo elige ella desde su perfil; se guarda con BCrypt y nadie más lo
--    ve (ADR 014). No es único en la empresa: en el kiosco se busca el nombre y
--    se teclea el PIN, así que elegir uno nunca revela el de otra persona.
--  - Cinco fallos seguidos lo bloquean quince minutos, por persona y no por IP:
--    la tablet entera comparte una.
--  - La tarjeta QR no guarda ningún secreto aquí: su contenido es una firma
--    HMAC del servidor sobre (id, versión). Regenerarla sube la versión y deja
--    sin valor la anterior. NULL = no tiene tarjeta.
ALTER TABLE usuarios
    ADD COLUMN kiosco_pin_hash            VARCHAR(100),
    ADD COLUMN kiosco_pin_fallos          INT NOT NULL DEFAULT 0,
    ADD COLUMN kiosco_pin_bloqueado_hasta TIMESTAMPTZ,
    ADD COLUMN kiosco_tarjeta_version     INT;

-- En qué kiosco se abrió la jornada, si se abrió en uno. Cada movimiento hecho
-- en un kiosco lo dice además en el motivo de su fila de auditoría, que entra
-- en la cadena de huellas (ADR 003 y 018).
ALTER TABLE registros
    ADD COLUMN kiosco_id BIGINT,
    ADD CONSTRAINT fk_registros_kiosco FOREIGN KEY (kiosco_id) REFERENCES kioscos(id);

GRANT SELECT, INSERT, UPDATE ON kioscos TO nxtime_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON kiosco_emparejamientos TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
