-- Entrar con Google o con Microsoft (ADR 036).
--
-- Cada fila dice «esta cuenta de Google (o de Microsoft) es de esta persona».
-- Con ella, quien ya tiene cuenta en NX Time entra sin teclear la contraseña.
-- No crea cuentas: a la gente la sigue dando de alta su empresa.
--
-- La primera vez se llega por el correo, que el proveedor da por verificado; a
-- partir de ahí manda el SUJETO, que es el identificador estable de la cuenta
-- en el proveedor. Si alguien cambia de correo en Google, sigue entrando; y si
-- su correo viejo pasa a otra persona, esa otra persona NO entra en su cuenta.
--
-- Es dato personal: identifica una cuenta de la persona en un tercero. Se borra
-- al ejecutar un borrado de datos (PersonalDataEraser).

CREATE TABLE identidades_externas (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,

    proveedor   VARCHAR(20)  NOT NULL,

    -- El `sub` del ID token. Opaco: Google manda unas 21 cifras y Microsoft
    -- una cadena de unos 43 caracteres. Ninguno promete un tamaño.
    sujeto      VARCHAR(255) NOT NULL,

    -- El correo de esa cuenta cuando se vinculó, para enseñarlo en «Cuentas
    -- vinculadas» («Google · ana@gmail.com»). No se usa para decidir nada.
    correo      VARCHAR(320) NOT NULL,

    vinculada_en  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ultimo_acceso TIMESTAMPTZ,

    CONSTRAINT fk_identidades_externas_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT ck_identidades_externas_proveedor CHECK (proveedor IN ('GOOGLE', 'MICROSOFT')),

    -- Una cuenta de Google es de una sola persona de NX Time. Es lo que impide
    -- que la misma cuenta abra dos sesiones distintas según por dónde se mire.
    CONSTRAINT uq_identidades_externas_sujeto UNIQUE (proveedor, sujeto),

    -- Y una persona tiene, como mucho, una cuenta de cada proveedor: «entrar
    -- con Google» tiene que significar una sola cosa.
    CONSTRAINT uq_identidades_externas_usuario UNIQUE (usuario_id, proveedor)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON identidades_externas TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
