-- Fase 8 (auditoría inalterable de fichajes): el registro horario en
-- España (RD-ley 8/2019) exige conservar los registros 4 años y que
-- sean fiables. Ver el plan de profesionalización.

-- Soporte de correcciones en "registros": una corrección NUNCA
-- sobrescribe horaEntrada/horaSalida -- anula la fila original y crea
-- una nueva con los valores correctos, enlazada a la que corrige.
ALTER TABLE registros ADD COLUMN anulado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE registros ADD COLUMN registro_original_id BIGINT REFERENCES registros(id) ON DELETE RESTRICT;

-- Tabla de auditoría, append-only: valor_anterior/valor_nuevo guardan
-- una instantánea JSON del fichaje antes/después de cada cambio.
-- hash/hash_anterior encadenan cada fila con la anterior (ver
-- TimeEntryAuditListener) para poder detectar una manipulación hecha
-- directamente en la base de datos, saltándose la aplicación.
CREATE TABLE auditoria_fichaje (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id         BIGINT       NOT NULL REFERENCES registros(id) ON DELETE RESTRICT,
    usuario_id          BIGINT       NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    modificado_por_id   BIGINT       NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    accion              VARCHAR(20)  NOT NULL CHECK (accion IN ('CREACION', 'MODIFICACION', 'CORRECCION', 'ANULACION')),
    valor_anterior      JSONB,
    valor_nuevo         JSONB,
    motivo              TEXT,
    fecha_hora          TIMESTAMPTZ  NOT NULL,
    ip                  VARCHAR(45),
    hash_anterior       VARCHAR(64),
    hash                VARCHAR(64)  NOT NULL,

    CONSTRAINT uq_auditoria_fichaje_hash UNIQUE (hash)
);

CREATE INDEX idx_auditoria_fichaje_registro ON auditoria_fichaje (registro_id, fecha_hora);

-- Refuerzo a nivel de PostgreSQL, no solo por convención en el código
-- Java (ver TimeEntryAudit, TimeEntryAuditRepository): el rol con el
-- que se conecta la aplicación en tiempo de ejecución ("nxtime_app",
-- creado en docker-entrypoint-initdb.d/init-app-role.sql -- ver ese
-- fichero, y application-dev.yml/application-prod.yml para el porqué
-- de separar el usuario de Flyway del de runtime) NO recibe ni UPDATE
-- ni DELETE sobre esta tabla. Ni un bug futuro en el código Java, con
-- las credenciales normales de la aplicación, puede alterar o borrar
-- una fila de auditoría ya escrita.
--
-- Importante: esto migra como "nxtime" (el rol de Flyway, con
-- privilegios de creación de esquema) y GRANTea explícitamente a
-- "nxtime_app" -- si el propio "nxtime_app" hubiera creado la tabla,
-- sería su dueño, y un dueño tiene privilegios implícitos que ningún
-- REVOKE puede quitarle. Por eso Flyway migra con un rol distinto del
-- que usa la aplicación en runtime.
GRANT SELECT, INSERT ON auditoria_fichaje TO nxtime_app;

-- El resto de tablas del esquema sí necesitan UPDATE/DELETE en
-- runtime (cambiar el estado de una ausencia, dar de baja a un
-- empleado, revocar un refresh token...). Se conceden aquí, en vez de
-- en las migraciones donde se crearon (V1/V2, anteriores a que
-- existiera "nxtime_app"), porque este es el primer punto del
-- historial de migraciones en que ese rol ya existe.
GRANT SELECT, INSERT, UPDATE, DELETE ON empresas, usuarios, registros, peticiones_ausencia, refresh_tokens TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;

-- Para que las tablas de fases futuras (9 en adelante) no necesiten
-- acordarse de repetir este GRANT cada vez: cualquier tabla/secuencia
-- que "nxtime" cree a partir de ahora concede automáticamente los
-- mismos privilegios a "nxtime_app". (auditoria_fichaje, creada arriba
-- en esta misma migración, no se ve afectada por este ALTER DEFAULT
-- PRIVILEGES -- solo aplica a objetos creados DESPUÉS de declararlo --
-- de ahí el GRANT explícito y más restringido, sin UPDATE/DELETE, que
-- ya se le dio unas líneas más arriba.)
-- Sin "FOR ROLE": así aplica al rol que esté ejecutando la migración,
-- sea cual sea. Antes decía "FOR ROLE nxtime", el nombre del rol de
-- docker-compose, y eso hacía la migración NO PORTABLE: al desplegar en
-- Neon fallaba con 'role "nxtime" does not exist', porque allí el dueño
-- se llama "neondb_owner". Un fichero de migración no debe conocer el
-- nombre del rol de un entorno concreto.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nxtime_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO nxtime_app;
