-- Fase 9 (lógica de negocio ampliada): trazabilidad de la aprobación de
-- ausencias, calendario laboral, saldo de vacaciones, jornada esperada y
-- detección de fichajes sin cerrar. Ver el plan de profesionalización.

-- ---------------------------------------------------------------------
-- Trazabilidad de la resolución de una ausencia
-- ---------------------------------------------------------------------
-- Antes no quedaba constancia de QUIÉN aprobó/rechazó ni CUÁNDO: la
-- petición simplemente cambiaba de estado (ver auditoría del plan).
ALTER TABLE peticiones_ausencia ADD COLUMN aprobado_por_id BIGINT REFERENCES usuarios(id) ON DELETE RESTRICT;
ALTER TABLE peticiones_ausencia ADD COLUMN fecha_resolucion TIMESTAMPTZ;
ALTER TABLE peticiones_ausencia ADD COLUMN comentario_resolucion TEXT;

-- Coherencia a nivel de BD, no solo en el código: una petición resuelta
-- tiene siempre resolutor y fecha; una PENDIENTE, nunca.
--
-- NOT VALID a propósito: las peticiones que ya estaban resueltas ANTES
-- de esta migración no tienen (ni pueden tener) resolutor -- esa
-- información nunca se registró, y rellenarla con un usuario cualquiera
-- sería inventarse un dato de trazabilidad, justo lo contrario de lo
-- que busca esta fase. Con NOT VALID, PostgreSQL no revisa las filas
-- existentes pero SÍ aplica la restricción a todo INSERT/UPDATE a
-- partir de ahora: lo viejo se queda como está, lo nuevo cumple.
ALTER TABLE peticiones_ausencia ADD CONSTRAINT ck_peticiones_resolucion_coherente CHECK (
    (estado = 'PENDIENTE' AND aprobado_por_id IS NULL AND fecha_resolucion IS NULL)
    OR (estado <> 'PENDIENTE' AND aprobado_por_id IS NOT NULL AND fecha_resolucion IS NOT NULL)
) NOT VALID;

-- ---------------------------------------------------------------------
-- Jornada esperada por empleado
-- ---------------------------------------------------------------------
-- Base para detectar incidencias (ver plan). 40 h/semana es la jornada
-- máxima ordinaria en España (art. 34 ET), buen valor por defecto.
ALTER TABLE usuarios ADD COLUMN horas_semanales NUMERIC(4,1) NOT NULL DEFAULT 40.0
    CHECK (horas_semanales > 0 AND horas_semanales <= 60);

-- ---------------------------------------------------------------------
-- Detección de fichajes incompletos
-- ---------------------------------------------------------------------
-- Una jornada que nunca se cerró (el empleado se fue sin fichar la
-- salida). Hasta ahora se quedaba abierta PARA SIEMPRE, y además
-- bloqueaba los fichajes siguientes: el índice parcial único
-- uq_registros_jornada_abierta impide una segunda jornada abierta, así
-- que el empleado no podía volver a fichar nunca más. Lo cierra el
-- @Scheduled nocturno (ver IncompleteTimeEntryScheduler), marcándolo
-- para que RRHH lo corrija con PATCH /api/v1/fichaje/{id} (Fase 8).
ALTER TABLE registros ADD COLUMN jornada_incompleta BOOLEAN NOT NULL DEFAULT FALSE;

-- La auditoría admite ahora acciones automáticas del sistema, sin autor
-- humano (el cierre nocturno de arriba): modificado_por_id pasa a ser
-- NULL-able, y NULL significa exactamente eso -- "lo hizo el sistema",
-- no "no se sabe quién".
ALTER TABLE auditoria_fichaje ALTER COLUMN modificado_por_id DROP NOT NULL;

-- ---------------------------------------------------------------------
-- Calendario laboral (festivos)
-- ---------------------------------------------------------------------
-- empresa_id NULL = festivo nacional, aplicable a todas las empresas.
-- Con valor = festivo propio de esa empresa (autonómico, local o de
-- convenio). Así una misma tabla cubre los dos casos sin duplicar filas
-- nacionales por cada empresa.
CREATE TABLE festivos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  BIGINT       REFERENCES empresas(id) ON DELETE RESTRICT,
    fecha       DATE         NOT NULL,
    descripcion VARCHAR(200) NOT NULL
);

-- Dos índices únicos parciales en vez de uno normal: en PostgreSQL,
-- UNIQUE (empresa_id, fecha) NO impide duplicar festivos nacionales,
-- porque NULL nunca es igual a NULL a efectos de unicidad.
CREATE UNIQUE INDEX uq_festivos_empresa_fecha ON festivos (empresa_id, fecha) WHERE empresa_id IS NOT NULL;
CREATE UNIQUE INDEX uq_festivos_nacional_fecha ON festivos (fecha) WHERE empresa_id IS NULL;
CREATE INDEX idx_festivos_fecha ON festivos (fecha);

-- ---------------------------------------------------------------------
-- Saldo de vacaciones
-- ---------------------------------------------------------------------
-- Solo se guarda el DERECHO anual (dias_totales); los días consumidos
-- se calculan sobre las peticiones APROBADAS de ese año, no se guardan.
-- Guardar un contador de consumidos obligaría a mantenerlo sincronizado
-- en cada aprobación, rechazo o corrección -- y cualquier fallo dejaría
-- el saldo mintiendo en silencio. Derivarlo tiene una única fuente de
-- verdad (ver VacationBalanceService).
CREATE TABLE saldo_vacaciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT  NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    anio         INTEGER NOT NULL,
    dias_totales INTEGER NOT NULL CHECK (dias_totales >= 0),

    CONSTRAINT uq_saldo_vacaciones_usuario_anio UNIQUE (usuario_id, anio)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON festivos, saldo_vacaciones TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
