-- Fase A (avisos dentro de la aplicación): las notificaciones dejan de
-- vivir SOLO en el correo.
--
-- Hasta ahora un empleado se enteraba de que le habían aprobado unas
-- vacaciones únicamente por email (Fase 10, ver
-- notification/NotificationListener). Si ese correo no llegaba -- SMTP
-- caído, buzón lleno, carpeta de spam -- no quedaba ni rastro dentro de
-- la aplicación: EmailSender se traga los fallos a propósito, porque un
-- correo es una cortesía y no puede tumbar una operación ya confirmada.
-- El precio de esa decisión era que el aviso podía evaporarse sin que
-- nadie se enterase. Guardarlo también aquí lo arregla sin renunciar a
-- nada: el MISMO evento que dispara el correo escribe la fila.
--
-- La otra mitad de esta fase -- la ficha de empleado editable -- NO
-- necesita DDL: usuarios.horas_semanales y la tabla saldo_vacaciones
-- existen desde V4__business_rules.sql, con sus CHECK puestos. Lo que
-- faltaba era un endpoint que las escribiera; hasta hoy nadie llamaba
-- nunca a vacationBalanceRepository.save().

-- ---------------------------------------------------------------------
-- Avisos dentro de la aplicación
-- ---------------------------------------------------------------------
-- "ruta_destino" guarda un destino LÓGICO ("ausencias-equipo/pendientes"),
-- no la ruta de navegación de un cliente concreto. Guardar aquí la ruta
-- literal de Compose ataría el servidor a la versión instalada de la
-- app: un aviso escrito hoy dejaría de funcionar en cuanto esa ruta se
-- renombrase, y obligaría además a codificar los argumentos en un
-- formato que solo entiende Navigation (ver el companion object de
-- Pantalla: URLEncoder produce "+" donde Navigation espera "%20", y eso
-- ya rompió una pantalla una vez). El cliente traduce el símbolo a su
-- propio grafo y, si no lo conoce, deja el aviso legible pero no
-- navegable. Puede ser NULL: hay avisos que solo informan.
--
-- "empresa_id" es redundante -- se deduce del destinatario -- y se
-- guarda a propósito: permite acotar o purgar por empresa sin join, y
-- es el mismo criterio denormalizado que ya sigue peticiones_ausencia
-- desde la Fase 3.
CREATE TABLE avisos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,
    destinatario_id BIGINT       NOT NULL,
    tipo            VARCHAR(40)  NOT NULL,
    titulo          VARCHAR(200) NOT NULL,
    cuerpo          TEXT         NOT NULL,
    ruta_destino    VARCHAR(120),
    leido           BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_avisos_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_avisos_destinatario
        FOREIGN KEY (destinatario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,

    -- OJO para las fases siguientes: cada tipo nuevo de aviso obliga a
    -- ampliar este CHECK en su propia migración, o el primer INSERT
    -- revienta. El acoplamiento es deliberado -- es lo que impide que
    -- un typo en el enum de Java meta basura en la columna.
    CONSTRAINT ck_avisos_tipo CHECK (tipo IN (
        'AUSENCIA_SOLICITADA',
        'AUSENCIA_RESUELTA',
        'BIENVENIDA'
    ))
);

-- Índice PARCIAL, no completo. La campana pregunta sin parar "¿cuántos
-- avisos sin leer tengo?", y esa consulta solo mira filas con
-- leido = false. Un índice sobre (destinatario_id, leido) a secas
-- crecería para siempre con el histórico YA LEÍDO -- que con el tiempo
-- es la práctica totalidad de la tabla -- para responder a una pregunta
-- que nunca lo consulta. Y dentro de un índice con WHERE leido = FALSE
-- la columna "leido" es constante por definición, así que no se repite.
CREATE INDEX idx_avisos_no_leidos ON avisos (destinatario_id) WHERE leido = FALSE;

-- La lista completa va acotada al destinatario y ordenada por fecha
-- descendente; sin este índice sería un recorrido secuencial de los
-- avisos de TODA la instalación para pintar los de una sola persona.
CREATE INDEX idx_avisos_destinatario_creado ON avisos (destinatario_id, creado_en DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON avisos TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
