-- Fase B1 (perfil de empleado): datos personales y departamentos.
--
-- Hasta ahora un usuario era cuatro cosas: email, nombre, rol y empresa.
-- Suficiente para fichar, pero no para que la aplicación tenga una
-- ficha de persona -- que es lo que necesitan la B2 (CV y foto) y la
-- fase H (ofertas internas, que se publican para un departamento).
--
-- Los adjuntos NO entran aquí: van en su propia migración junto con la
-- tabla de bytes, para que este cambio siga siendo puramente aditivo y
-- reversible sin tocar datos binarios.

-- ---------------------------------------------------------------------
-- Departamentos
-- ---------------------------------------------------------------------
-- Por empresa, no globales: dos empresas del mismo tenant pueden tener
-- ambas un "Operaciones" sin que sean el mismo, igual que pasa con los
-- festivos de convenio (ver V4).
CREATE TABLE departamentos (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT       NOT NULL,
    nombre     VARCHAR(100) NOT NULL,

    CONSTRAINT fk_departamentos_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT uq_departamentos_empresa_nombre UNIQUE (empresa_id, nombre)
);

-- ---------------------------------------------------------------------
-- Datos personales del usuario
-- ---------------------------------------------------------------------
-- Todos NULL: son datos que la persona rellena cuando quiere, y una
-- plantilla entera ya dada de alta no tiene ninguno. Poner NOT NULL con
-- un valor por defecto inventado sería peor que no saberlo -- un puesto
-- vacío se puede pedir, un puesto que dice "Empleado" porque lo puso
-- una migración parece un dato y no lo es.
--
-- "apellidos" va aparte de "nombre" y no concatenado: la fase H ordena
-- candidaturas y un listado de RRHH se ordena por apellido, cosa que un
-- campo único no permite sin partir cadenas a ojo.
ALTER TABLE usuarios ADD COLUMN apellidos        VARCHAR(150);
ALTER TABLE usuarios ADD COLUMN fecha_nacimiento DATE;
ALTER TABLE usuarios ADD COLUMN puesto           VARCHAR(120);
ALTER TABLE usuarios ADD COLUMN departamento_id  BIGINT;

ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_departamento
    FOREIGN KEY (departamento_id) REFERENCES departamentos(id) ON DELETE RESTRICT;

-- ON DELETE RESTRICT y no SET NULL a propósito: borrar un departamento
-- con gente dentro debe fallar y obligar a moverla primero, no vaciarle
-- el campo a media plantilla en silencio.
CREATE INDEX idx_usuarios_departamento ON usuarios (departamento_id);

-- Que la fecha de nacimiento no esté en el futuro se valida en el DTO
-- (@Past) y NO aquí: PostgreSQL exige que las funciones de un CHECK
-- sean IMMUTABLE, y CURRENT_DATE es STABLE -- la restricción ni
-- siquiera se dejaría crear. Tampoco se comprueba la edad mínima: la
-- edad laboral tiene excepciones (art. 6 ET) y una restricción de base
-- de datos no es el sitio para decidirlas.

GRANT SELECT, INSERT, UPDATE, DELETE ON departamentos TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
