-- Fase B2: el CV y la foto de perfil.
--
-- Los bytes van en PostgreSQL y no en un bucket externo (ver ADR 007).
-- Resumen: el disco de Render es efímero, así que un fichero escrito
-- hoy no está mañana; y un bucket mete credenciales de un tercero en
-- una demo que tiene que poder levantarse con un docker compose. Para
-- un CV de 5 MB y una foto de 30 KB por persona, la base aguanta de
-- sobra.

-- ---------------------------------------------------------------------
-- Metadatos del adjunto
-- ---------------------------------------------------------------------
-- UNIQUE(usuario_id, tipo): un CV y una foto VIGENTES por persona.
-- Subir otro reemplaza el anterior en vez de acumular versiones -- la
-- app no ofrece un historial de currículums, y guardarlo sin que nadie
-- pueda verlo sería solo ocupar espacio.
--
-- OJO para la fase H: una candidatura congela el adjunto_id del CV de
-- ese momento, así que el reemplazo tendrá que dejar de borrar la fila
-- vieja cuando alguien la referencie. Hoy no hay quien lo haga.
CREATE TABLE adjuntos (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      BIGINT       NOT NULL,
    usuario_id      BIGINT       NOT NULL,
    tipo            VARCHAR(20)  NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    mime            VARCHAR(100) NOT NULL,
    tamano_bytes    BIGINT       NOT NULL CHECK (tamano_bytes > 0),
    subido_en       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_adjuntos_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_adjuntos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT ck_adjuntos_tipo CHECK (tipo IN ('CV', 'FOTO')),
    CONSTRAINT uq_adjuntos_usuario_tipo UNIQUE (usuario_id, tipo)
);

-- ---------------------------------------------------------------------
-- Los bytes, en su propia tabla
-- ---------------------------------------------------------------------
-- Esta es la parte que no es evidente y conviene no "simplificar" luego.
--
-- Si el bytea viviera en la fila de "adjuntos", Hibernate lo cargaría en
-- CADA findById aunque nadie pida el contenido: listar los adjuntos de
-- una empresa se traería todos los currículums a memoria. La solución
-- habitual -- @Basic(fetch = LAZY) sobre el campo binario -- SOLO
-- funciona con bytecode enhancement de Hibernate, que en este proyecto
-- no está activado; sin él la anotación no da error, simplemente se
-- ignora, que es la peor forma de fallar.
--
-- Con dos tablas, la entidad Adjunto no ve nunca el contenido y este se
-- sirve con una consulta propia cuando alguien lo descarga.
--
-- PK = FK: la fila de bytes no tiene identidad propia, es el cuerpo del
-- adjunto. Y ON DELETE CASCADE, al revés que el RESTRICT de todo lo
-- demás: borrar el adjunto tiene que llevarse sus bytes, o quedarían
-- huérfanos sin que nadie pueda alcanzarlos ni borrarlos.
CREATE TABLE adjunto_datos (
    adjunto_id BIGINT PRIMARY KEY,
    contenido  BYTEA  NOT NULL,

    CONSTRAINT fk_adjunto_datos_adjunto
        FOREIGN KEY (adjunto_id) REFERENCES adjuntos(id) ON DELETE CASCADE
);

CREATE INDEX idx_adjuntos_usuario ON adjuntos (usuario_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON adjuntos, adjunto_datos TO nxtime_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nxtime_app;
